version: "3.3"

services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./local-data:/home/local-data
    ports:
      - 27017:27017

  web:
    image: lifzzz/phalcon-mongo:1.0
    volumes:
      - ./smltools:/var/www/html/smltools/
    ports:
      - 8000:80
    depends_on:
      - mongo

