<p><?php $this->flashSession->output() ?></p>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <div class="formshow hero card-shadow reveal white">
         <h1 class="textCenter">Login</h1>
         <?php
            echo $this->tag->form(
              [
                "Auth/signin",
                "autocomplete" => "off",
                "id" => "signin-form"
              ]
            );
            ?>
         <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
            value="<?php echo $this->security->getToken() ?>"/>
         <form id="signin-form">
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Username</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user" aria-hidden="true"></i></span>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Password</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-key" aria-hidden="true"></i></span>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" >
                     </div>
                  </div>
               </div>
            </div>
            <!-- 
               <div class="form-group row">
                  <label for="username" class="col-sm-2 col-form-label">Username</label>
                  <div class="col-sm-10">
                     <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
                  </div>
               </div>
               <div class="form-group row">
                  <label for="password" class="col-sm-2 col-form-label">Password</label>
                  <div class="col-sm-10">
                     <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                  </div>
               </div> -->
            <!-- <div class="form-group row">
               <div class="col-sm-2">Checkbox</div>
               <div class="col-sm-10">
                  <div class="form-check">
                     <label class="form-check-label">
                     <input class="form-check-input" type="checkbox"> Check me out
                     </label>
                  </div>
               </div>
               </div> -->
            <!-- <div class="form-group row">
               <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary" id="signin">Sign in</button>
               </div>
               </div> -->
            <button type="submit" class="btn btn-info pull-right" id="signin">Sign in</button>
         </form>
      </div>
   </div>
</div>