<div class="formshow hero card-shadow reveal white">
<h1 class="textCenter">Login</h1>
<?php
   echo $this->tag->form(
     [
       "Auth/signin",
       "autocomplete" => "off",
       "id" => "signin-form"
     ]
   );
   ?>
<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
   value="<?php echo $this->security->getToken() ?>"/>

<form id="signin-form">
   <div class="form-group row">
      <label for="username" class="col-sm-2 col-form-label">Username</label>
      <div class="col-sm-10">
         <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
      </div>
   </div>
   <div class="form-group row">
      <label for="password" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
         <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
   </div>
   <!-- <div class="form-group row">
      <div class="col-sm-2">Checkbox</div>
      <div class="col-sm-10">
         <div class="form-check">
            <label class="form-check-label">
            <input class="form-check-input" type="checkbox"> Check me out
            </label>
         </div>
      </div>
   </div> -->
   <div class="form-group row">
      <div class="col-sm-10">
         <button type="submit" class="btn btn-primary" id="signin">Sign in</button>
      </div>
   </div>
</form>
</div>