
<div class="formshow hero card-shadow reveal white">
<h1 class="textCenter">Register</h1>
  <div id="error"></div>
  <form id="signup-form">
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
    </div>

    
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="name">Name</label>
        <input type="text" class="form-control" name="name" id="name" placeholder="Name" >
      </div>
      <div class="form-group col-md-6">
        <label for="sirname">Lastname</label>
        <input type="text" class="form-control" name="sirname" id="sirname" placeholder="Lastname" >
      </div>
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email" id="email" placeholder="Email" >
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password" >
      </div>
      <div class="form-group col-md-6">
        <label for="password2">Confirm-Password</label>
        <input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm-Password" >
      </div>
    </div>
    <button type="submit" class="btn btn-info" id="signup">Sign up</button>
  </form>
</div>