<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <div class="formshow hero card-shadow reveal white">
         <h1 class="textCenter">Register</h1>
         <div id="error"></div>
         <form id="signup-form">
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Username</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user" aria-hidden="true"></i></span>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-6">
                  <div class="form-group">
                     <label>Name</label>
                     <input type="text" class="form-control" name="name" id="name" placeholder="Name" >
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="form-group">
                     <label>Lastname</label>
                     <input type="text" class="form-control" name="sirname" id="sirname" placeholder="Lastname" >
                  </div>
               </div>
            </div>
         
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Email</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">@</span>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email" >
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-6">
                  <div class="form-group">
                     <label>Password</label>
                     <input type="password" class="form-control" name="password" id="password" placeholder="Password" >
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="form-group">
                     <label>Confirm-Password</label>
                     <input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm-Password" >
                  </div>
               </div>
            </div>
            <button type="button" class="btn btn-info pull-right" id="signup">Sign up</button>
         </form>
      </div>
   </div>
</div>