<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top"><i class="fa fa-fw fa-map-pin"></i>SML TOOLS</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto text-center">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
                </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#feature">Feature</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="register">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav> 


            <div class="formshow hero">   
                <h2 class="headform textCenter">Create Task</h2>           
                <?php
                    echo $this->tag->form(
                        [
                            "task/save",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                ?>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Task</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["taskname", "size" => 30, 
                            "class" => "form-control", "id" => "name" , "placeholder"=>"task name"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">isA</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["isA", "size" => 30, 
                            "class" => "form-control", "id" => "isA" , "placeholder"=>"isA"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Description</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textArea(["Description", "class" => "form-control", 
                            "id" => "Description" , "placeholder"=>"Description","rows" => 3,]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">includes</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["includes", "size" => 30, 
                            "class" => "form-control", "id" => "includes" , "placeholder"=>"includes"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">asIsState</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["asIsState", "size" => 30, 
                            "class" => "form-control", "id" => "asIsState" , "placeholder"=>"asIsState"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">owner</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["asIsState", "size" => 30, 
                            "class" => "form-control", "id" => "asIsState" , "placeholder"=>"asIsState"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">collaburator</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["collaburator", "size" => 30, 
                            "class" => "form-control", "id" => "collaburator" , "placeholder"=>"collaburator"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">regular</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["regular", "size" => 30, 
                            "class" => "form-control", "id" => "regular" , "placeholder"=>"regular"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">uses</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["uses", "size" => 30, 
                            "class" => "form-control", "id" => "uses" , "placeholder"=>"uses"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">produces</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["produces", "size" => 30, 
                            "class" => "form-control", "id" => "produces" , "placeholder"=>"produces"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toBeState</label>
                      <div class="col-sm-4">
                        <?php 
                            echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                            "id" => "toBeState" 
                            ,[
                                "E" => "EXIST",
                                "N" => "NEXIST",
                                "A" => "ADEPTED",
                            ]
                            ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">ownerToBe</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["ownerToBe", "size" => 30, 
                            "class" => "form-control", "id" => "ownerToBe" , "placeholder"=>"ownerToBe"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">collaboratorToBe</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["collaboratorToBe", "size" => 30, 
                            "class" => "form-control", "id" => "collaboratorToBe" , "placeholder"=>"collaboratorToBe"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toUse</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["toUse", "size" => 30, 
                            "class" => "form-control", "id" => "toUse" , "placeholder"=>"toUse"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toProduce</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["toProduce", "size" => 30, 
                            "class" => "form-control", "id" => "toProduce" , "placeholder"=>"toProduce"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
				      <div class="offset-sm-2 col-sm-10">
                        <?php 
                            echo $this->tag->submitButton(["Save", "size" => 30, 
                            "class" => "btn btn-primary", "id" => "btnsubmit"]) 
                        ?>
				      </div>
				    </div>
                <?php echo $this->tag->endForm(); ?>
            </div>