            <div class="formshow hero ">   
                <h2 class="headform textCenter">Create Task</h2>           
                <?php
                    echo $this->tag->form(
                        [
                            "task/test",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                ?>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Task</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["taskname", "size" => 30, 
                            "class" => "form-control", "id" => "taskname" , "placeholder"=>"task name"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">isA</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["isA", "size" => 30, 
                            "class" => "form-control", "id" => "isA" , "placeholder"=>"isA"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">Description</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textArea(["Description", "class" => "form-control", 
                            "id" => "Description" , "placeholder"=>"Description","rows" => 3,]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">includes</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["includes", "size" => 30, 
                            "class" => "form-control", "id" => "includes" , "placeholder"=>"includes"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">asIsState</label>
                      <div class="col-sm-6">
                      <?php 
                            echo $this->tag->selectStatic(["asIsState", "class" => "form-control", 
                            "id" => "asIsState" 
                            ,[
                                "E" => "EXIST",
                                "N" => "NEXIST",
                            ]
                            ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">owner</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["owner", "size" => 30, 
                            "class" => "form-control", "id" => "owner" ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">collaburator</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["collaburator", "size" => 30, 
                            "class" => "form-control", "id" => "collaburator" ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">regulator</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["regulator", "size" => 30, 
                            "class" => "form-control", "id" => "regulator"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">uses</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["uses", "size" => 30, 
                            "class" => "form-control", "id" => "uses" , "placeholder"=>"uses"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">produces</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["produces", "size" => 30, 
                            "class" => "form-control", "id" => "produces" , "placeholder"=>"produces"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toBeState</label>
                      <div class="col-sm-4">
                        <?php 
                            echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                            "id" => "toBeState" 
                            ,[
                                "E" => "EXIST",
                                "N" => "NEXIST",
                                "A" => "ADEPTED",
                            ]
                            ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">ownerToBe</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["ownerToBe", "size" => 30, 
                            "class" => "form-control", "id" => "ownerToBe"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">collaboratorToBe</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["collaboratorToBe", "size" => 30, 
                            "class" => "form-control", "id" => "collaboratorToBe" ]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toUse</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["toUse", "size" => 30, 
                            "class" => "form-control", "id" => "toUse"]) 
                        ?>
                      </div>
                              
                      <div class="float-right pl-3">
                        <button type="button" class="btn btn-active" data-toggle="modal" data-target="#exampleModal2">
                          <i class="fa fa-fw fa-plus"></i>
                        </button>
                      </div>

                    </div>
                    <div class="form-group row">
                      <label for="project" class="col-sm-2 col-form-label">toProduce</label>
                      <div class="col-sm-6">
                        <?php 
                            echo $this->tag->textField(["toProduce", "size" => 30, 
                            "class" => "form-control", "id" => "toProduce" , "placeholder"=>"toProduce"]) 
                        ?>
                      </div>
                    </div>
                    <div class="form-group row">
				              <div class="offset-sm-2 col-sm-10">
                       
                      </div>
                    </div>
				    
                <?php echo $this->tag->endForm(); ?>
                <?php 
                            echo $this->tag->submitButton(["saveTask", "size" => 30, 
                            "class" => "btn btn-primary", "id" => "saveTask"]) 
                        ?>
        </div>