<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
      <i class="fa fa-fw fa-map-pin"></i>SML TOOLS</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto text-center">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#feature">Feature</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="register">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<div class="formshow hero">
  <h2 class="headform textCenter">Edit Task</h2>
  <?php
                    echo $this->tag->form(
                        [
                            "task/save",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                ?>

    <?php 
                             echo $this->tag->hiddenField(["idtask", "id" => "idtask" , "value" => $idTask]) ;
          
                        ?>

    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">Task</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["taskname", "size" => 30, 
                            "class" => "form-control", "id" => "Edname" , "placeholder"=>"task name"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">isA</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["isA", "size" => 30, 
                            "class" => "form-control", "id" => "EdisA" , "placeholder"=>"isA"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">Description</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textArea(["Description", "class" => "form-control", 
                            "id" => "EdDescription" , "placeholder"=>"Description","rows" => 3,]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">includes</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["includes", "size" => 30, 
                            "class" => "form-control", "id" => "Edincludes" , "placeholder"=>"includes"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">asIsState</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->selectStatic(["asIsState", "class" => "form-control", 
                            "id" => "easIsState" 
                            ,[
                                "E" => "EXIST",
                                "N" => "NEXIST",
                            ]
                            ]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">owner</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["owner", "size" => 30, 
                            "class" => "form-control", "id" => "Edowner" ]) 
                        ?>

      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">collaburator</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["Edcollaburator", "size" => 30, 
                            "class" => "form-control", "id" => "Edcollaburator" ]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">regulator</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["regulator", "size" => 30, 
                            "class" => "form-control", "id" => "Edregulator"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">uses</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["uses", "size" => 30, 
                            "class" => "form-control", "id" => "Eduses" , "placeholder"=>"uses"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">produces</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["produces", "size" => 30, 
                            "class" => "form-control", "id" => "Edproduces" , "placeholder"=>"produces"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">toBeState</label>
      <div class="col-sm-4">
        <?php 
                            echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                            "id" => "EdtoBeState" 
                            ,[
                                "E" => "EXIST",
                                "N" => "NEXIST",
                                "A" => "ADEPTED",
                            ]
                            ]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">ownerToBe</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["EdownerToBe", "size" => 30, 
                            "class" => "form-control", "id" => "EdownerToBe"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">collaboratorToBe</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["EdcollaboratorToBe", "size" => 30, 
                            "class" => "form-control", "id" => "EdcollaboratorToBe" ]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">toUse</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["toUse", "size" => 30, 
                            "class" => "form-control", "id" => "EdtoUse"]) 
                        ?>
      </div>

      

    </div>
    <div class="form-group row">
      <label for="project" class="col-sm-2 col-form-label">toProduce</label>
      <div class="col-sm-6">
        <?php 
                            echo $this->tag->textField(["toProduce", "size" => 30, 
                            "class" => "form-control", "id" => "etoProduce" , "placeholder"=>"toProduce"]) 
                        ?>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <?php 
                            echo $this->tag->submitButton(["Save", "size" => 30, 
                            "class" => "btn btn-primary", "id" => "btnsubmittask"]) 
                        ?>
      </div>
    </div>


    <?php echo $this->tag->endForm(); ?>
</div>

<script>
                  
  var js_test = '<?php echo json_encode($test); ?>';
  js_test = JSON.parse(js_test);
  js_test = createJSON(js_test);
  js_test = JSON.stringify(js_test);
 
 
  var data_owner = '<?php echo json_encode($owner); ?>';
 
  var data_collaburator = '<?php echo json_encode($collaburator); ?>';
  
  var data_ownerTobe = '<?php echo json_encode($ownerTobe); ?>';
  var data_collaboratorTobe = '<?php echo json_encode($collaboratorTobe); ?>';
  
  

  $(document).ready(function(){

    var Stakeholder = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(js_test)
    });

    Stakeholder.initialize();

    var EdownerToBe = $('#EdownerToBe');
    EdownerToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(EdownerToBe, data_ownerTobe);


    var Edowner = $('#Edowner');
    Edowner.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(Edowner, data_owner);


    var Edcollaburator = $('#Edcollaburator');
    Edcollaburator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(Edcollaburator, data_collaburator);
   

    var EdcollaboratorToBe = $('#EdcollaboratorToBe');
    EdcollaboratorToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(EdcollaboratorToBe, data_collaboratorTobe);
 
});


  function add($elt, data){
      $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data.value, "text": data.name, "continent": "" });
      });
  }

  function createOwner($elt){
    $elt.tagsinput('add', { "value": 5555, "text": "new owner", "continent": "" });
  }

  function createJSON(data) {
        jsonObj = [];
        var i = 2;
        $.each(data, function(index ,data){

            item = {};
            item ["value"] = data.value;
            item ["text"] = data.name;
            item ["continent"] = "";
            item ["index"] = data._id.$id;
            i++;
            jsonObj.push(item);
        });

        item = {};
        item ["value"] = 0;
        item ["text"] = "?";
        item ["continent"] = "";
        jsonObj.push(item);
       
        return jsonObj;
  }
</script>