
<!-- new -->
<h2 class="headform textCenter">Edit Task</h2>
<?php
   echo $this->tag->form(
       [
         
           "autocomplete" => "off",
           "class" => "form-horizontal",
          
       ]
   );
   ?>
            <?php 
            echo $this->tag->hiddenField(["idProject", "id" => "EdidProject" ]);
            echo $this->tag->hiddenField(["idTask", "id" => "EdidTask" ]);
            ?>
<div class="content">
    <div class="container-fluid">
       <div class="row">
          <div class="col-md-9">
             <div class="card s-navShadow">
                <div class="header">
                   <h4 class="title">Create Task</h4>
                </div>
                <div class="content">
                   <form>
                      <div class="row">
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                                <?php 
                                  echo $this->tag->textField(["taskname", "size" => 30, 
                                  "class" => "form-control", "id" => "Edname" , "placeholder"=>"task name"]) 
                                ?>
                            </div>
                         </div>
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>IsA</label>
                                <?php 
                                  echo $this->tag->textField(["isA", "size" => 30, 
                                  "class" => "form-control", "id" => "EdisA" , "placeholder"=>"isA"]) 
                                ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-12">
                            <div class="form-group">
                               <label>Description</label>
                               <?php 
                                  echo $this->tag->textArea(["Description", "class" => "form-control", 
                                  "id" => "EdDescription" , "placeholder"=>"Description","rows" => 3,]) 
                                ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-8">
                            <div class="form-group">
                               <label>Includes</label>
                              
                               <div class="input-group">
                                  <?php 
                                    echo $this->tag->textField(["includes", "size" => 30, 
                                    "class" => "form-control", "id" => "Edincludes" , "placeholder"=>"includes"]) 
                                  ?>
                                   <div class="btn input-group-addon" style="border: 1px solid #9a9a9a;">+</div> 
                               </div>
                            </div>
                         </div>
                         <div class="col-md-4">
                            <div class="form-group">
                               <label>as IsState</label>
                                <?php 
                                    echo $this->tag->selectStatic(["asIsState", "class" => "form-control", 
                                    "id" => "EdasIsState" 
                                      ,[
                                          "E" => "EXIST",
                                          "N" => "NEXIST",
                                      ]
                                    ]) 
                                ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-4">
                            <div class="form-group">
                               <label>Owner</label>
                               <?php 
                                  echo $this->tag->textField(["owner", "size" => 30, 
                                  "class" => "form-control", "id" => "Edowner" ]) 
                                ?>
                            </div>
                         </div>
                         <div class="col-md-4">
                            <div class="form-group">
                               <label>Collaburator</label>
                               <?php 
                                echo $this->tag->textField(["collaburator", "size" => 30, 
                                "class" => "form-control", "id" => "Edcollaburator" ]) 
                               ?>     
                            </div>
                         </div>
                         <div class="col-md-4">
                            <div class="form-group">
                               <label>Regulator</label>
                               <?php 
                                  echo $this->tag->textField(["regulator", "size" => 30, 
                                  "class" => "form-control", "id" => "Edregulator"]) 
                              ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-8">
                            <div class="form-group">
                               <label>Uses</label>
                               <?php 
                                  echo $this->tag->textField(["uses", "size" => 30, 
                                  "class" => "form-control", "id" => "Eduses" , "placeholder"=>"uses"]) 
                               ?>
                            </div>
                         </div>
                         <div class="col-md-4">
                            <div class="form-group">
                               <label>to Be State</label>
                               <?php 
                                  echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                                  "id" => "EdtoBeState" 
                                  ,[
                                      "E" => "EXIST",
                                      "N" => "NEXIST",
                                      "A" => "ADEPTED",
                                  ]
                                  ]) 
                               ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-12">
                            <div class="form-group">
                               <label>Produces</label>
                               <?php 
                                    echo $this->tag->textField(["produces", "size" => 30, 
                                    "class" => "form-control", "id" => "Edproduces" , "placeholder"=>"produces"]) 
                               ?>
                            </div>
                         </div>
                      </div>
                     
                      <div class="row">
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>owner To Be</label>
                               <?php 
                                  echo $this->tag->textField(["ownerToBe", "size" => 30, 
                                  "class" => "form-control", "id" => "EdownerToBe"]) 
                               ?>
                            </div>
                         </div>
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>collaborator To Be</label>
                               <?php 
                                  echo $this->tag->textField(["collaboratorToBe", "size" => 30, 
                                  "class" => "form-control", "id" => "EdcollaboratorToBe" ]) 
                                ?>
                            </div>
                         </div>
                      </div>
                      <div class="row">
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>toUse</label>
                               <?php 
                                  echo $this->tag->textField(["toUse", "size" => 30, 
                                  "class" => "form-control", "id" => "EdtoUse"]) 
                               ?>
                            </div>
                         </div>
                         <div class="col-md-6">
                            <div class="form-group">
                               <label>toProduce</label>
                               <?php 
                                  echo $this->tag->textField(["toProduce", "size" => 30, 
                                  "class" => "form-control", "id" => "EdtoProduce" , "placeholder"=>"toProduce"]) 
                               ?>
                            </div>
                         </div>
                      </div>
                      <?php echo $this->tag->endForm(); ?>
                      <button type="submit" class="btn btn-info btn-fill pull-right" id="editTask">Save</button>
                      <div class="clearfix"></div>
                   </form>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>













<!-- blockJS -->
<script>
    
    var stakeinput = '<?php echo json_encode($stake); ?>';
    
    stakeinput = JSON.parse(stakeinput);
    stakeinput = createJSON(stakeinput);
    stakeinput = JSON.stringify(stakeinput);
    
 
  var data_owner = '<?php echo json_encode($owner); ?>';
 
  var data_collaburator = '<?php echo json_encode($collaburator); ?>';
  
  var data_ownerTobe = '<?php echo json_encode($ownerTobe); ?>';
  var data_collaboratorTobe = '<?php echo json_encode($collaboratorTobe); ?>';
  console.log(data_owner);
  

  $(document).ready(function(){

    var Stakeholder = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(stakeinput)
    });
  
    Stakeholder.initialize();

    var EdownerToBe = $('#EdownerToBe');
    EdownerToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(EdownerToBe, data_ownerTobe);


    var Edowner = $('#Edowner');
    Edowner.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(Edowner, data_owner);


    var Edcollaburator = $('#Edcollaburator');
    Edcollaburator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(Edcollaburator, data_collaburator);
   

    var EdcollaboratorToBe = $('#EdcollaboratorToBe');
    EdcollaboratorToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(EdcollaboratorToBe, data_collaboratorTobe);

});


  function add($elt, data){
      $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name, "continent": "" });
      });
  }

  function createOwner($elt){
    $elt.tagsinput('add', { "value": 5555, "text": "new owner", "continent": "" });
  }

  function createJSON(data) {
        jsonObj = [];
        
        $.each(data, function(index ,data){

            item = {};
            item ["value"] = data._id.$id;
            item ["text"] = data.name;
            item ["continent"] = "";
           
            jsonObj.push(item);
        });

        item = {};
        item ["value"] = 0;
        item ["text"] = "?";
        item ["continent"] = "";
        jsonObj.push(item);
       
        return jsonObj;
  }
</script>
<!-- /.blockJS -->