
<!-- new -->
<h2 class="headform textCenter">Edit Task</h2>
<?php
   echo $this->tag->form(
       [
         
           "autocomplete" => "off",
           "id" => "editTask-form"
       ]
   );
   ?>
            <?php 
            echo $this->tag->hiddenField(["idProject", "id" => "EdidProject" ]);
            echo $this->tag->hiddenField(["idTask", "id" => "EdidTask" ]);
            ?>
 <div class="content">
  <div class="container-fluid">
     <div class="row">
        <div class="col-md-12">
           <div class="card s-navShadow">
              <div class="row">
                 <div class="col-md-8 col-md-offset-2">
                    <div class="header">
                       <h4 class="title">Edit Task</h4>
                    </div>
                    <div class="content">
                       <form>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                                   <?php 
                                      echo $this->tag->textField(["taskname", "size" => 30, 
                                      "class" => "form-control", "id" => "Edname"]) 
                                  ?>
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>IsA</label>
                                   <?php 
                                    echo $this->tag->textField(["isA", "size" => 30, 
                                    "class" => "form-control", "id" => "EdisA" ]) 
                                  ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-12">
                                <div class="form-group">
                                   <label>Description</label>
                                   <?php 
                                      echo $this->tag->textArea(["Description", "class" => "form-control", 
                                      "id" => "EdDescription","rows" => 3,]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-8">
                                <div class="form-group">
                                   <label>Includes</label>
                                  <?php 
                                      echo $this->tag->textField(["includes", "size" => 30, 
                                      "class" => "form-control", "id" => "Edincludes"]) 
                                  ?>
                                       <a href="<?=$this->url->get("task/create"); ?>"class="fa fa-plus iconInput"></a>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>as IsState</label>
                                    <?php 
                                        echo $this->tag->selectStatic(["asIsState", "class" => "form-control", 
                                        "id" => "EdasIsState" 
                                          ,[
                                              "E" => "EXIST",
                                              "N" => "NEXIST",
                                          ]
                                        ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Owner</label>
                                   <?php 
                                      echo $this->tag->textField(["owner", "size" => 30, 
                                      "class" => "form-control", "id" => "Edowner" ]) 
                                    ?>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Collaburator</label>
                                   <?php 
                                      echo $this->tag->textField(["collaburator", "size" => 30, 
                                      "class" => "form-control", "id" => "Edcollaburator" ]) 
                                  ?>   
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Regulator</label>
                                    <?php 
                                      echo $this->tag->textField(["regulator", "size" => 30, 
                                      "class" => "form-control", "id" => "Edregulator"]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-8">
                                <div class="form-group">
                                   <label>Uses</label>
                                   <?php 
                                      echo $this->tag->textField(["uses", "size" => 30, 
                                      "class" => "form-control", "id" => "Eduses" ]) 
                                    ?>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>to Be State</label>
                                    <?php 
                                        echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                                        "id" => "EdtoBeState" 
                                          ,[
                                              "E" => "EXIST",
                                              "N" => "NEXIST",
                                              "A" => "ADEPTED",
                                          ]
                                        ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-12">
                                <div class="form-group">
                                   <label>Produces</label>
                                   <?php 
                                        echo $this->tag->textField(["produces", "size" => 30, 
                                        "class" => "form-control", "id" => "Edproduces" ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>owner To Be</label>
                                   <?php 
                                      echo $this->tag->textField(["ownerToBe", "size" => 30, 
                                      "class" => "form-control", "id" => "EdownerToBe"]) 
                                    ?>
                                    
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>collaborator To Be</label>
                                   <?php 
                                      echo $this->tag->textField(["collaboratorToBe", "size" => 30, 
                                      "class" => "form-control", "id" => "EdcollaboratorToBe" ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>toUse</label>
                                   <?php 
                                      echo $this->tag->textField(["toUse", "size" => 30, 
                                      "class" => "form-control", "id" => "EdtoUse"]) 
                                    ?>
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>toProduce</label>
                                   <?php 
                                      echo $this->tag->textField(["toProduce", "size" => 30, 
                                      "class" => "form-control", "id" => "EdtoProduce"]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <?php echo $this->tag->endForm(); ?>
                          <button type="submit" class="btn btn-info btn-fill pull-right" id="editTask">Save</button>
                          <div class="clearfix"></div>
                       </form>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>
</div>
<div class="modal createStakeholder" id="createStakeholder" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">New Stakeholder</h4>
            <button class="btn btn-info" onclick="cloneModal($('#createStakeholder'))">+</button>
         </div>
         <div class="modal-body">
            <ul class="nav nav-tabs">
               <li class="active"><a data-toggle="tab" href="#Organisation">Organisation</a></li>
               <li><a data-toggle="tab" href="#Individual">Individual</a></li>
               <li><a data-toggle="tab" href="#Role">Role</a></li>
            </ul>
            <div class="tab-content">
               <div id="Organisation" class="tab-pane fade in active">
                  <h3>Organisation</h3>
                  <div class="content">
                     <form>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>Name</label>
                                 <input type="text" class="form-control">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>Organisation</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>aka</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>description</label>
                                 <textarea rows="5" class="form-control" ></textarea>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>concern</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>representative</label>
                                 <input type="text" class="form-control">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>reports</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>consults</label>
                                 <input type="text" class="form-control">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>liaises</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>delegate</label>
                                 <input type="text" class="form-control">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>dTask</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>wishes</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="clearfix"></div>
                     </form>
                  </div>
               </div>
               <div id="Individual" class="tab-pane fade">
                  <h3>Individual</h3>
                  <div class="content">
                     <form>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>Name</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>aka</label>
                                 <input type="text" class="form-control" >
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>description</label>
                                 <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>concern</label>
                                 <input type="text" class="form-control" placeholder="it's concern...">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>attitude</label>
                                 <select class="form-control" name="category">
                                    <option>select</option>
                                    <option>positive</option>
                                    <option>neutral</option>
                                    <option>negative</option>
                                    <option>?</option>
                                 </select>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>domain Knowledge</label>
                                 <select class="form-control" name="category">
                                    <option>select</option>
                                    <option>novice</option>
                                    <option>intermediate</option>
                                    <option>expert</option>
                                    <option>?</option>
                                 </select>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>reports</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>consults</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>liaises</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>delegate</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>dTask</label>
                                 <input type="text" class="form-control" placeholder="Task name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>wishes</label>
                                 <input type="text" class="form-control" placeholder="goal name">
                              </div>
                           </div>
                        </div>
                        <div class="clearfix"></div>
                     </form>
                  </div>
               </div>
               <div id="Role" class="tab-pane fade">
                  <h3>Role</h3>
                  <div class="content">
                     <form>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>Name</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>aka</label>
                                 <input type="text" class="form-control" placeholder="it's alias me..">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>is A</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>description</label>
                                 <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>concern</label>
                                 <input type="text" class="form-control" placeholder="it's concern...">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>PlayerType</label>
                                 <select class="form-control" name="category">
                                    <option>select</option>
                                    <option>Only one</option>
                                    <option>One</option>
                                    <option>Any</option>
                                    <option>Group</option>
                                 </select>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>RolePlayer</label>
                                 <select class="form-control" name="category">
                                    <option>select</option>
                                    <option>All</option>
                                    <option>Some</option>
                                    <option>Any</option>
                                 </select>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>reports</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>consults</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>liaises</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>delegate</label>
                                 <input type="text" class="form-control" placeholder="Stakeholder name">
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>dTask</label>
                                 <input type="text" class="form-control" placeholder="Task name">
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>wishes</label>
                                 <input type="text" class="form-control" placeholder="goal name">
                              </div>
                           </div>
                        </div>
                        <div class="clearfix"></div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- Modal Resource-->
<div class="modal createResource" id="createResource" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">New Resource</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <form>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <input type="hidden" name="idProjectmodalResource" value="<?=$idProject?>" id="idProjectmodalResource">
                           <label>Resource Name</label>
                           <?php 
                              echo $this->tag->textField(["resourcename", "size" => 30, 
                              "class" => "form-control", "id" => "Modalresourcename"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>description</label>
                           <?php 
                              echo $this->tag->textArea(["Description", "class" => "form-control", 
                               "id" => "ModalDesResource" ,"rows" => 3,]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>includes</label>
                           <?php 
                              echo $this->tag->textField(["includes", "size" => 30, 
                              "class" => "form-control ModalincludesResource", "id" => "ModalincludesResource"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>r Owner</label>
                           <?php 
                              echo $this->tag->textField(["rOwner", "size" => 30, 
                              "class" => "form-control", "id" => "ModalrOwnerResource"]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>p Owner</label>
                           <?php 
                              echo $this->tag->textField(["pOwner", "size" => 30, 
                              "class" => "form-control", "id" => "ModalpOwnerResource"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>Maintainer</label>
                           <?php 
                              echo $this->tag->textField(["maintainer", "size" => 30, 
                              "class" => "form-control", "id" => "ModalmaintainerResource"]) 
                              ?>    
                        </div>
                     </div>
                  </div>
                  <div class="clearfix"></div>
               </form>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-info" id="saveResourceformModal">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>


<!-- ================================  modal Tasks  ============================================ -->

<div class="modal createTask" id="createTask" role="dialog">
      <div class="modal-dialog">
         <!-- Modal content-->
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title">New Task</h4>
            </div>
            <div class="modal-body">
               <div class="content">
                  <form>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                              <input type="hidden" name="idProjectmodalTask" value="<?=$idProject?>" id="idProjectmodalTask">
                                 <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                                 <?php 
                                    echo $this->tag->textField(["Modaltaskname", "size" => 30, 
                                    "class" => "form-control", "id" => "Modaltaskname" , ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>IsA</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalIsATask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalIsATask" ,]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>Description</label>
                                 <?php 
                                    echo $this->tag->textArea(["ModalDescriptionTask", "class" => "form-control", 
                                     "id" => "ModalDescriptionTask" ,"rows" => 3,]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-8">
                              <div class="form-group">
                                 <label>Includes</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalincludesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalincludesTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>as IsState</label>
                                 <?php 
                                    echo $this->tag->selectStatic(["ModalasIsStateTask", "class" => "form-control", 
                                    "id" => "ModalasIsStateTask" 
                                    ,[
                                        "E" => "EXIST",
                                        "N" => "NEXIST",
                                    ]
                                    ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Owner</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalOwnerTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalOwnerTask" ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Collaburator</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalCollaburatorTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalCollaburatorTask" ]) 
                                    ?>  
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Regulator</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalRegulatorTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalregulatorTask"]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-8">
                              <div class="form-group">
                                 <label>Uses</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalUsesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalUsesTask" ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>to Be State</label>
                                 <?php 
                                    echo $this->tag->selectStatic(["ModalToBeStateTask", "class" => "form-control", 
                                    "id" => "ModalToBeStateTask" 
                                    ,[
                                        "E" => "EXIST",
                                        "N" => "NEXIST",
                                        "A" => "ADEPTED",
                                    ]
                                    ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>Produces</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalProducesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalProducesTask" ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>owner To Be</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalOwnerToBeTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalOwnerToBeTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>collaborator To Be</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalCollaboratorToBeTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalCollaboratorToBeTask" ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>toUse</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalToUseTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalToUseTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>toProduce</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalToProduceTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalToProduceTask"]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                     </form>
               </div>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-info" id="saveTaskformModal">Save</button>
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
         </div>
      </div>
   </div>











<!-- blockJS -->
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script>
      $("#createTaskIcon").click(function(){
            cloneModalTask($('#createTask'));
      })
</script>
<script>
       questionMark($('#Edincludes'));
       questionMark($('#Edowner'));
       questionMark($('#Edcollaburator'));
       questionMark($('#Edregulator'));
       questionMark($('#Eduses'));
       questionMark($('#Edproduces'));
       questionMark($('#EdownerToBe'));
       questionMark($('#EdcollaboratorToBe'));
       questionMark($('#EdtoUse'));
       questionMark($('#EdtoProduce'));
</script>
<script>
    var taskinput = '<?php echo json_encode($taskTags); ?>';
    taskinput = JSON.parse(taskinput);
    taskinput = createJSON(taskinput);
    taskinput = JSON.stringify(taskinput);

    var data_includes = '<?php echo json_encode($includes); ?>';


    var stakeinput = '<?php echo json_encode($tagsStake); ?>';
    stakeinput = JSON.parse(stakeinput);
    stakeinput = createJSON(stakeinput);
    stakeinput = JSON.stringify(stakeinput);

    var data_owner = '<?php echo json_encode($owner); ?>';
    var data_collaburator = '<?php echo json_encode($collaburator); ?>';
    var data_regulator = '<?php echo json_encode($regulator); ?>';
    var data_ownerTobe = '<?php echo json_encode($ownerTobe); ?>';
    var data_collaboratorTobe = '<?php echo json_encode($collaboratorTobe); ?>';

             
    var resourceinput = '<?php echo json_encode($resourceTags); ?>';
    resourceinput = JSON.parse(resourceinput);
    resourceinput = createJSON(resourceinput);
    resourceinput = JSON.stringify(resourceinput);

    var data_uses = '<?php echo json_encode($uses); ?>';
    var data_produces = '<?php echo json_encode($produces); ?>';
    var data_toUse = '<?php echo json_encode($toUse); ?>';
    var data_toProduces = '<?php echo json_encode($toProduce); ?>';
   

  $(document).ready(function(){

      Tasks = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(taskinput)
    });
    Tasks.initialize();
    
    var Edincludes = $('#Edincludes');
    Edincludes.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Tasks.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalTask($(\'#createTask\'))"> No matches.</div>'
        },
      }
    });
    add(Edincludes, data_includes);


      Stakeholder = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(stakeinput)
    });
  
    Stakeholder.initialize();

    var EdownerToBe = $('#EdownerToBe');
    EdownerToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(EdownerToBe, data_ownerTobe);


    var Edowner = $('#Edowner');
    Edowner.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edowner, data_owner);


    var Edcollaburator = $('#Edcollaburator');
    Edcollaburator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edcollaburator, data_collaburator);


    var Edregulator = $('#Edregulator');
    Edregulator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edregulator, data_regulator);
   

    var EdcollaboratorToBe = $('#EdcollaboratorToBe');
    EdcollaboratorToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(EdcollaboratorToBe, data_collaboratorTobe);


      Resource = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(resourceinput)
    });
  
    Resource.initialize();
    var Eduses = $('#Eduses');
    Eduses.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(Eduses, data_uses);


    var Edproduces = $('#Edproduces');
    Edproduces.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(Edproduces, data_produces);


    var EdtoUse = $('#EdtoUse');
    EdtoUse.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(EdtoUse, data_toUse);
   

    var EdtoProduce = $('#EdtoProduce');
    EdtoProduce.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(EdtoProduce, data_toProduces);

    

});


  function add($elt, data){
      $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name, "continent": "" });
      });
  }



</script>

<!-- /.blockJS -->