
<div class="ui grid">
   <div class="ten wide column">
      <div class="ui cards">
         <div class="ui raised link card">
            <div class="content">
               <div class="header">Task name</div>
               <div class="description">
                  Task detailed
               </div>
            </div>
            <div class="ui bottom attached button">
               <i class="add icon"></i>
               Manage Task
            </div>
         </div>
        
      </div>
   </div>
   <div class="five wide column">
      <div class="ui raised segments">   
         <div class="ui segment very padded">
            <h2 class="ui header">
        
                <div class="content">
                    Search Task
                    <div class="sub header">Search your projects</div>
                </div>
            </h2>
            <div class="ui search">
               <div class="ui icon input">
                  <input class="prompt" type="text" placeholder="project name...">
                  <i class="search icon"></i>
               </div>
               <div class="results"></div>
            </div>
            
         </div>
        
      <div class="ui segment very padded">
            <h2 class="ui header">
        
                <div class="content">
                    Search Stakeholder
                    <div class="sub header">Search Stakeholder</div>
                </div>  
            </h2>
            <div class="ui search">
               <div class="ui icon input">
                  <input class="prompt" type="text" placeholder="project name...">
                  <i class="search icon"></i>
               </div>
               <div class="results"></div>
            </div>
            
         </div>
      </div>
   </div>
</div>