<?php
   echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]);
   echo $this->tag->hiddenField(["idStake", "id" => "idStake" ]);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="header">
                            <h4 class="title">Edit Organisation</h4>
                        </div>
                        <div class="content">
                            <form id="edit_organisation">
                                <label>
                                    <?php if($focal == 1) { ?>
                                    <input type="checkbox" id="focal" checked> Focal Organisation
                                    <?php }else{ ?>
                                    <input type="checkbox" id="focal"> Focal Organisation
                                    <?php }?>
                                </label>
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="form-group">
                                            <label>Name</label>
                                            <?php
                                        echo $this->tag->textField(["edStakeName", "size" => 30,
                                        "class" => "form-control", "id" => "edStakeName" ])
                                        ?>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Layer</label>
                                            <?php
                                                echo $this->tag->selectStatic(["layerWorld", "class" => "form-control",
                                                "id" => "OrLayerWorld"
                                                ,$LayerWorld ])
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Organisation</label>
                                            <?php
                                        echo $this->tag->textField(["edOrganName", "size" => 30,
                                        "class" => "form-control", "id" => "OrganName" ])
                                        ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>aka</label>

                                            <?php
                                        echo $this->tag->textField(["edOaka", "size" => 30,
                                        "class" => "form-control", "id" => "Oaka" ])
                                        ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>description</label>

                                            <?php
                                        echo $this->tag->textArea(["edOdescription", "rows" => 3,
                                        "class" => "form-control", "id" => "Odescription" ])
                                        ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>concern</label>

                                            <?php
                                        echo $this->tag->textField(["edOconcern", "size" => 30,
                                        "class" => "form-control", "id" => "Oconcern" ])
                                        ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>representative</label>
                                            <?php
                                                echo $this->tag->textField(["edOrepresentative", "size" => 30,
                                                "class" => "form-control", "id" => "edOrepresentative" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>reports</label>
                                            <?php
                                                echo $this->tag->textField(["edOreports", "size" => 30,
                                                "class" => "form-control", "id" => "edOreports" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>consults</label>
                                            <?php
                                                echo $this->tag->textField(["edOconsults", "size" => 30,
                                                "class" => "form-control", "id" => "edOconsults" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>liaises</label>
                                            <?php
                                                echo $this->tag->textField(["edOliaises", "size" => 30,
                                                "class" => "form-control", "id" => "edOliaises" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>delegate</label>
                                            <?php
                                                echo $this->tag->textField(["edOdelegate", "size" => 30,
                                                "class" => "form-control", "id" => "edOdelegate" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>dTask</label>
                                            <?php
                                                echo $this->tag->textField(["edOdTask", "size" => 30,
                                                "class" => "form-control", "id" => "edOdTask" ])
                                            ?>
                                            <i class="fa fa-plus iconInput createTaskIcon"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>wishes</label>

                                            <?php
                                        echo $this->tag->textField(["edOwishes", "size" => 30,
                                        "class" => "form-control", "id" => "Owishes" ])
                                        ?>
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn btn-info btn-fill pull-right" id="Save_edit_Organ">Save Organisation</button>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- blockJS -->
        <script>
            $(".createTaskIcon").click(function(){
                cloneModalTask($('#createTask'));
            });

            $(".createResourceIcon").click(function(){
                cloneModalResource($('#createResource'));
            });

            $(".createStakeholderIcon").click(function(){
                cloneModalStakeholder($('#createStakeholder'));
            });
            var taskinput = '<?php echo json_encode($taskTags); ?>';
            taskinput = JSON.parse(taskinput);
            taskinput = createJSON(taskinput);
            taskinput = JSON.stringify(taskinput);

            var data_dTask = '<?php echo json_encode($dTask); ?>';


            var stakeinput = '<?php echo json_encode($tagsStake); ?>';
            stakeinput = JSON.parse(stakeinput);
            stakeinput = createJSON(stakeinput);
            stakeinput = JSON.stringify(stakeinput);

            var data_reports = '<?php echo json_encode($reports); ?>';
            var data_consults = '<?php echo json_encode($consults); ?>';
            var data_liaises = '<?php echo json_encode($liaises); ?>';
            var data_delegate = '<?php echo json_encode($delegate); ?>';

            var stakerepersent = '<?php echo json_encode($tagsRepresent); ?>';
            stakerepersent = JSON.parse(stakerepersent);
            stakerepersent = createJSON(stakerepersent);
            stakerepersent = JSON.stringify(stakerepersent);

            var data_representative = '<?php echo json_encode($representative); ?>';

            $(document).ready(function () {
                Tasks_Edit = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    local: JSON.parse(taskinput)
                });
                Tasks_Edit.initialize();

                var edOdTask = $('#edOdTask');
                edOdTask.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Tasks_Edit.ttAdapter(),
                        templates: {
                            empty: '<div id="nomatch" class="empty-message text-info" onclick="cloneModalTask($(\'#createTask\'))"> No matches.</div>'
                        }
                    }
                });
                add(edOdTask, data_dTask);

                Stakeholder_Edit = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    local: JSON.parse(stakeinput)
                });
                Stakeholder_Edit.initialize();

                var edOreports = $('#edOreports');
                edOreports.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Stakeholder_Edit.ttAdapter(),
                        templates: {
                            highlight: true,
                            empty: '<div class="empty-message text-info add-stakeholder" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                        }
                    }
                });
                add(edOreports, data_reports);

                var edOconsults = $('#edOconsults');
                edOconsults.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Stakeholder_Edit.ttAdapter(),
                        templates: {
                            highlight: true,
                            empty: '<div class="empty-message text-info add-stakeholder" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                        }
                    }
                });
                add(edOconsults, data_consults);

                var edOliaises = $('#edOliaises');
                edOliaises.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Stakeholder_Edit.ttAdapter(),
                        templates: {
                            empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                        }
                    }
                });
                add(edOliaises, data_liaises);

                var edOdelegate = $('#edOdelegate');
                edOdelegate.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Stakeholder_Edit.ttAdapter(),
                        templates: {
                            empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                        },
                    }
                });
                add(edOdelegate, data_delegate);

                var edOrepresentative = $('#edOrepresentative');
                edOrepresentative.tagsinput({
                    itemValue: 'value',
                    itemText: 'text',
                    typeaheadjs: {
                        name: 'name',
                        displayKey: 'text',
                        source: Stakeholder_Edit.ttAdapter(),
                        templates: {
                            empty: '<div id="nomatch" class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                        }
                    }
                });
                add(edOrepresentative, data_representative);
            });

            function add($elt, data) {
                $.each(JSON.parse(data), function (index, data) {
                    $elt.tagsinput('add', {
                        "value": data._id.$id,
                        "text": data.name
                    });
                });
            }

            questionMark($('#edOrepresentative'));
            questionMark($('#edOreports'));
            questionMark($('#edOconsults'));
            questionMark($('#edOliaises'));
            questionMark($('#edOdelegate'));
            questionMark($('#edOdTask'));
        </script>
        <!-- /.blockJS -->