
<p><?php $this->flashSession->output() ?></p>
<!-- <div class="wrapper"> -->
<div class="container-fluid">
   <!-- <div class="container"> -->
   <div class="row">
      <div class="col-md-12">
         <a href="<?=$this->url->get("stakeholder/create"); ?>" class="labelAdd btn btn-Primary pull-right"><i class="fa fa-plus"></i></a>
      </div>
   </div>
   <div class="row" style="margin-top: 50px">
      <div class="col-md-9">
         <div class="fresh-table s-navShadow">
            <table id="fresh-table" class="table">
               <thead>
                  <th data-field="id">No.</th>
                  <th data-field="name" data-sortable="true">Name</th>
                  <th data-sortable="true">Role</th>
                  <th data-sortable="true">Task</th>
                  <th data-sortable="true">Resource</th>
                  <th data-sortable="true">Stakeholder</th>
                  <th data-formatter="" data-events="operateEvents" class="pull-right">Manage Actions</th>
               </thead>
               <tbody>
                  <?php
                     $i =1;
                     foreach($stakeholders->items['cursor']['firstBatch'] as $key => $showStake) {  ?>
                  <tr>
                     <td><?= $i ?></td>
                     <td>
                        <h6 style="color: #747474"><?=$showStake['name'] ?></h6>
                     </td>
                     <td>
                        <?php
                        if($showStake['type'] == '1' or $showStake['type'] =='0')
                            echo 'organisation';
                        elseif($showStake['type'] =='2')
                            echo 'individual';
                        else
                            echo 'role';
                        ?>
                     </td>
                     <td><?=$showStake['sumStake']?></td>
                     <td><?=$showStake['sumResource']?></td>
                     <td><?=$showStake['sumStake']?></td>
                     <td>
                        <a onclick="confirm('Are you sure delete <?=$showStake['name']?>?')?deleteStake('<?=$showStake['_id']?>'):false;" class="btn btn-danger btn-xs pull-right labelDanger" role="button" style="margin-left: 3px;" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>&nbsp;
                        <a href="#" class="btn btn-primary btn-xs pull-right labelPrimary stakeedit" data-id="<?=$showStake['_id']?>" role="button" data-toggle="tooltip"  data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                        <a class="showDetailStake btn btn-xs pull-right"  data-id="<?=$showStake['_id']?>"  role="button" style="margin-right: 3px;" data-toggle="tooltip" data-placement="top" title="Show"><i class="fa fa-eye"></i></a>&nbsp;
                     </td>
                  </tr>
                  <?php  $i++; } ?>
               </tbody>
            </table>
         </div>
      </div>
      <form action="<?=$this->url->get("stakeholder/index"); ?>" method="POST">
         <div class="col-md-3">
            <!-- Sort -->
            <div class="card s-navShadow">
               <div class="header">
                  <h4 class="title">Sort</h4>
               </div>
               <div class="content">
                  <div class="form-group">
                     <!-- <label for="sel1">Select list (select one):</label> -->
                     <?php
                        echo $this->tag->select(
                                [
                                        'sortBy',
                                        $arrSortBy,
                                        'value' => $sortBy,
                                        'class' => 'form-control',
                                        'id' => 'sel1',
                                        'onchange' => 'this.form.submit()'
                                ]
                        );
                        ?>
                  </div>
               </div>
            </div>
            <!-- Filter -->
            <div class="card s-navShadow">
               <div class="header">
                  <h4 class="title">Filter</h4>
               </div>
               <div class="content">
                  <div class="form-group">
                     <div class="form-group">
                        <label>Stakeholder Name</label>
                        <input type="text" class="form-control" name="filter" placeholder="Stakeholder Name" value="<?=$filter?>">
                     </div>
                  </div>
                  <div class="footer">
                     <button class="btn btn-default pull-right" type="submit">Filter</button>
                  </div>
               </div>
            </div>
         </div>
      </form>
   </div>
   <!-- </div> -->
</div>
<?php echo $stakeholders->widgetPagination; ?>
<!-- </div> -->
<!-- choose modal  -->
<!-- Organization -->
<div class="modal showStake" id="showStake" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content card">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Organisation Details</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <div class="row">
                  <div class="col-md-12">
                     <label>Name</label>
                     <h5 id="showStakeName"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Organisation name</label>
                     <h5 id="showStakeOrganization"></h5>
                  </div>
                  <div class="col-md-6">
                     <label>AKA</label>
                     <h5 id="showStakeAka"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <label>Description</label>
                     <h5 id="showStakeDescription"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <label>Concern</label>
                     <h5 id="showStakeConcern"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Representative</label>
                     <h5 id="showStakeRepresentative"></h5>
                  </div>
                  <div class="col-md-6">
                     <label>Reports</label>
                     <h5 id="showStakeReports"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Consults</label>
                     <h5 id="showStakeConsults"></h5>
                  </div>
                  <div class="col-md-6">
                     <label>Liaises</label>
                     <h5 id="showStakeLiaises"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Delegate</label>
                     <h5 id="showStakeDelegate"></h5>
                  </div>
                  <div class="col-md-6">
                     <label>Dtask</label>
                     <h5 id="showStakeDtask"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <label>Wishes</label>
                     <h5 id="showStakeWishes"></h5>
                  </div>
               </div>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- Individual -->
<!-- role -->
<!-- blockJS -->
<script>
   function deleteStake(id){
       var idStake = id;
       console.log('test');
       $.post(baseUrl+"stakeholder/deleteStakeholder",{
           idStake : idStake
       }, function(data){
        window.location.href = baseUrl+"stakeholder";
       },  "json");

   }
</script>
<!-- /.blockJS -->