<div class="container-fluid">
   <ul class="nav nav-tabs" id="myTabs" role="tablist" style="
      border-bottom: 0px">
      <li role="presentation" class="active"><a href="#organisation" id="organisation-tab" role="tab" data-toggle="tab" aria-controls="organisation" aria-expanded="true" >Organisation</a></li>
      <li role="presentation" class=""><a href="#individual" role="tab" id="individual-tab" data-toggle="tab" aria-controls="individual" aria-expanded="false">Individual</a></li>
      <li role="presentation" class=""><a href="#role" role="tab" id="role-tab" data-toggle="tab" aria-controls="role" aria-expanded="false">Role</a></li>
   </ul>
   <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade active in" role="tabpanel" id="organisation" aria-labelledby="organisation-tab">
         <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-6 col-md-offset-3">
                        <div class="header">
                           <h4 class="title">Create organisation</h4>
                        </div>
                        <div class="content">
                           <form>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>Name</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder Name...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Organisation</label>
                                       <input type="text" class="form-control" placeholder="Organisation name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       <input type="text" class="form-control" placeholder="it's alias me">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       <input type="text" class="form-control" placeholder="it's concern...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>representative</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder Name...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       <input type="text" class="form-control" placeholder="Task name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       <input type="text" class="form-control" placeholder="goal name">
                                    </div>
                                 </div>
                              </div>
                              <button type="submit" class="btn btn-info btn-fill pull-right">Save Organisation</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="tab-pane fade" role="tabpanel" id="individual" aria-labelledby="individual-tab">
         <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-6 col-md-offset-3">
                        <div class="header">
                           <h4 class="title">Create individual</h4>
                        </div>
                        <div class="content">
                           <form>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Name</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       <input type="text" class="form-control" placeholder="it's alias me..">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       <input type="text" class="form-control" placeholder="it's concern...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>attitude</label>
                                       <select class="form-control" name="category">
                                          <option>select</option>
                                          <option>positive</option>
                                          <option>neutral</option>
                                          <option>negative</option>
                                          <option>?</option>
                                       </select>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>domain Knowledge</label>
                                       <select class="form-control" name="category">
                                          <option>select</option>
                                          <option>novice</option>
                                          <option>intermediate</option>
                                          <option>expert</option>
                                          <option>?</option>
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       <input type="text" class="form-control" placeholder="Task name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       <input type="text" class="form-control" placeholder="goal name">
                                    </div>
                                 </div>
                              </div>
                              <button type="submit" class="btn btn-info btn-fill pull-right">Save Individual</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="tab-pane fade" role="tabpanel" id="role" aria-labelledby="role-tab">
         <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-6 col-md-offset-3">
                        <div class="header">
                           <h4 class="title">Create Role</h4>
                        </div>
                        <div class="content">
                           <form>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Name</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       <input type="text" class="form-control" placeholder="it's alias me..">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>is A</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       <input type="text" class="form-control" placeholder="it's concern...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>PlayerType</label>
                                       <select class="form-control" name="category">
                                          <option>select</option>
                                          <option>Only one</option>
                                          <option>One</option>
                                          <option>Any</option>
                                          <option>Group</option>
                                       </select>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>RolePlayer</label>
                                       <select class="form-control" name="category">
                                          <option>select</option>
                                          <option>All</option>
                                          <option>Some</option>
                                          <option>Any</option>
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       <input type="text" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       <input type="text" class="form-control" placeholder="Task name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       <input type="text" class="form-control" placeholder="goal name">
                                    </div>
                                 </div>
                              </div>
                              <button type="submit" class="btn btn-info btn-fill pull-right">Save Role</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- blockJS -->
<script>
   $(document).ready(function(){
        $('#myTabs a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
        })
        
   });
</script>
<!-- /.blockJS -->