<div class="container-fluid">
      <div class="row  mb-3">
        <!-- Card Layout -->
        <div class="col-md-12 col-sm-12 order-md-1 order-sm-1 order-2">
          <div class="card">
            <div class="card-body">
              <ul class="nav nav-tabs" id="myTab3" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" id="pills-test2-tab" href="creOrgan" role="tab" aria-expanded="true">Organisation</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="pills-test2-tab" href="creIndiv" role="tab" aria-expanded="true">Individual</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="pills-test1-tab" href="creRole" role="tab" aria-expanded="true">Role</a>
                </li>
              </ul>

              <div class="tab-content mt-3" id="myTab3Content">
                <div class="tab-pane fade show active" id="pills-test1" role="tabpanel" aria-labelledby="pills-test1-tab">
					<div class="row">
			          <div class="col-12 mb-4">
			            <div class="">
			              <div class="card-body">
			                <div class="">
			                <!-- container -->
			                  <form>
			                  	<div class="form-group row">
			                      <div class="col-sm-2">
			                      	name
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="Organisation" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	Organisation
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="Organisation" placeholder="organisation name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	aka
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="aka" placeholder="its alias name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	def
			                      </div>
			                      <div class="col-sm-6">
			                      	<textarea class="form-control" id="description" rows="3"></textarea>
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	concern
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="concern" placeholder="its concerns">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	representative
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="representative" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	reports
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	consults
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	liaises
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	delegate
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="stakeholder name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	dTask
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="task name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
			                      <div class="col-sm-2">
			                      	wishes
			                      </div>
			                      <div class="col-sm-6">
			                      	<input type="text" class="form-control" id="reports" placeholder="goal name">
			                      </div>
			                    </div>
			                    <div class="form-group row">
							      <div class="offset-sm-2 col-sm-10">
							        <button type="submit" class="btn btn-primary">Save</button>
							      </div>
							    </div>
			                  </form>
			                </div>
			              </div>
			            </div>
			          </div>
			
			        </div>
                
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.Card Layout -->

      </div>
    </div>