<?php 
   echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]) 
?>
<div class="container-fluid">
<div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-8 col-md-offset-2">
                        <div class="header">
                           <h4 class="title">Create organisation</h4>
                        </div>
                        <div class="content">
                           <form>
                            <label>
                                <input type="checkbox" id="focal"> Focal Organisation
                            </label>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>Name</label>
                                       <?php 
                                        echo $this->tag->textField(["edStakeName", "size" => 30, 
                                        "class" => "form-control", "id" => "edStakeName" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Organisation</label>
                                       <input type="text" class="form-control" name="OrganName" id="OrganName" placeholder="Organisation name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       <input type="text" class="form-control" name="Oaka" id="Oaka" placeholder="it's alias me">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       <textarea rows="5" class="form-control" name="Odescription" id="Odescription" placeholder="Here can be your description"></textarea>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       <input type="text" class="form-control" name="Oconcern" id="Oconcern" placeholder="it's concern...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>representative</label>
                                       <input type="text" class="form-control" name="Orepresentative" id="Orepresentative" placeholder="">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       <input type="text" class="form-control" name="Oreports" id="Oreports" placeholder="">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       <input type="text" class="form-control" name="Oconsults" id="Oconsults" placeholder="">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       <input type="text" class="form-control" name="Oliaises" id="Oliaises" placeholder="">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       <input type="text" class="form-control" name="Odelegate" id="Odelegate" placeholder="">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       <input type="text" class="form-control" name="OdTask" id="OdTask" placeholder="">
                                    </div>
                                 </div>
                                 </div>
                                 <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       <input type="text" class="form-control" name="Owishes" id="Owishes" placeholder="goal name">
                                    </div>
                                 </div>
                              </div>
                              <button type="button" class="btn btn-info btn-fill pull-right" id="SaveOr">Save Organisation</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
</div>

