<?php 
   echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]) 
?>
<div class="container-fluid">
    <div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-8 col-md-offset-2">
                        <div class="header">
                           <h4 class="title">Create individual</h4>
                        </div>
                        <div class="content">
                           <form>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Name</label>
                                       <input type="text" name="inStakeName" id="inStakeName" class="form-control" placeholder="Stakeholder name">
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       <input type="text" name="inaka" id="inaka" class="form-control" placeholder="it's alias me..">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       <textarea rows="5" name="indescription" id="indescription" class="form-control" placeholder="Here can be your description"></textarea>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       <input type="text" name="inconcern" id="inconcern" class="form-control" placeholder="it's concern...">
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>attitude</label>
                                       <select class="form-control" name="attitude" id="attitude">
                                          <option>select</option>
                                          <option value="0">positive</option>
                                          <option value="1">neutral</option>
                                          <option value="2">negative</option>
                                          <option value="?">?</option>
                                       </select>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>domain Knowledge</label>
                                       <select class="form-control" name="domainKnowledge" id="domainKnowledge">
                                          <option>select</option>
                                          <option value="0">novice</option>
                                          <option value="1">intermediate</option>
                                          <option value="2">expert</option>
                                          <option value="?">?</option>
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       <input type="text" name="inreports" id="inreports" class="form-control" >
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       <input type="text" name="inconsults" id="inconsults" class="form-control" >
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       <input type="text" name="inliaises" id="inliaises" class="form-control" >
                                    </div>
                                 </div>
                                </div>
                                <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       <input type="text" name="indelegate" id="indelegate" class="form-control" >
                                    </div>
                                 </div>

                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       <input type="text" name="indTask" id="indTask" class="form-control" placeholder="">
                                    </div>
                                 </div>
                                 </div>
                                 <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       <input type="text" name="inwishes" id="inwishes" class="form-control" placeholder="goal name">
                                    </div>
                                 </div>
                              </div>
                              <button  class="btn btn-info btn-fill pull-right" id="Savein">Save Individual</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      
</div>