<?php 
   echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]);
   echo $this->tag->hiddenField(["idStake", "id" => "idStake" ]);
?>
<div class="container-fluid">
<div class="row">
            <div class="col-md-12">
               <div class="card">
                  <div class="row">
                     <div class="col-md-8 col-md-offset-2">
                        <div class="header">
                           <h4 class="title">Edit Role</h4>
                        </div>
                        <div class="content">
                           <form>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>Name</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrStakeName", "size" => 30, 
                                        "class" => "form-control", "id" => "rStakeName" ]) 
                                        ?>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>aka</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edraka", "size" => 30, 
                                        "class" => "form-control", "id" => "raka" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>is A</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edisA", "size" => 30, 
                                        "class" => "form-control", "id" => "isA" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>description</label>
                                       
                                        <?php 
                                        echo $this->tag->textArea(["edrdescription", "rows" => 3, 
                                        "class" => "form-control", "id" => "rdescription" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>concern</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrconcern", "size" => 30, 
                                        "class" => "form-control", "id" => "rconcern" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>PlayerType</label>
                                       
                                       <?php 
                                        echo $this->tag->selectStatic(["edPlayerType", "class" => "form-control", 
                                        "id" => "PlayerType" 
                                          ,[
                                              "0" => "Only one",
                                              "1" => "One",
                                              "2" => "Any",
                                              "3" => "Group",
                                          ],
                                          "useEmpty" => true,
                                          "emptyText"  => "select",
                                        ]) 
                                        ?>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>RolePlayer</label>
                                       <?php 
                                        echo $this->tag->selectStatic(["edRolePlayer", "class" => "form-control", 
                                        "id" => "RolePlayer" 
                                          ,[
                                              "0" => "All",
                                              "1" => "Some",
                                              "2" => "Any",
                                          ],
                                          "useEmpty" => true,
                                          "emptyText"  => "select",
                                        ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>reports</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrreports", "size" => 30, 
                                        "class" => "form-control", "id" => "edrreports" ]) 
                                        ?>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>consults</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrconsults", "size" => 30, 
                                        "class" => "form-control", "id" => "edrconsults" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>liaises</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrliaises", "size" => 30, 
                                        "class" => "form-control", "id" => "edrliaises" ]) 
                                        ?>
                                    </div>
                                 </div>
                                </div>
                                <div class="row">
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>delegate</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrdelegate", "size" => 30, 
                                        "class" => "form-control", "id" => "edrdelegate" ]) 
                                        ?>
                                    </div>
                                 </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                       <label>dTask</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrdTask", "size" => 30, 
                                        "class" => "form-control", "id" => "edrdTask" ]) 
                                        ?>
                                    </div>
                                 </div>
                                 </div>
                                 <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <label>wishes</label>
                                       
                                       <?php 
                                        echo $this->tag->textField(["edrwishes", "size" => 30, 
                                        "class" => "form-control", "id" => "rwishes" ]) 
                                        ?>
                                    </div>
                                 </div>
                              </div>
                              <button  class="btn btn-info btn-fill pull-right" id="saveedR">Save Role</button>
                              <div class="clearfix"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
</div>
<!-- blockJS -->
<script>

var taskinput = '<?php echo json_encode($taskTags); ?>';
    taskinput = JSON.parse(taskinput);
    taskinput = createJSON(taskinput);
    taskinput = JSON.stringify(taskinput);

    var data_dTask = '<?php echo json_encode($dTask); ?>';


    var stakeinput = '<?php echo json_encode($tagsStake); ?>';
    stakeinput = JSON.parse(stakeinput);
    stakeinput = createJSON(stakeinput);
    stakeinput = JSON.stringify(stakeinput);

    
    var data_reports = '<?php echo json_encode($reports); ?>';
    var data_consults = '<?php echo json_encode($consults); ?>';
    var data_liaises = '<?php echo json_encode($liaises); ?>';
    var data_delegate = '<?php echo json_encode($delegate); ?>';



    $(document).ready(function(){
        Tasks = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: JSON.parse(taskinput)
        });
        Tasks.initialize();

        var edrdTask = $('#edrdTask');
        edrdTask.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'name',
                displayKey: 'text',
                source: Tasks.ttAdapter(),
                templates: {
                    empty: '<div id="nomatch" class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                }
            }
        });
        add(edrdTask, data_dTask);

        Stakeholder = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            local: JSON.parse(stakeinput)
        });
        Stakeholder.initialize();

        var edrreports = $('#edrreports');
        edrreports.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'name',
                displayKey: 'text',
                source: Stakeholder.ttAdapter(),
                templates: {
                    highlight: true,
                    empty: '<div class="empty-message text-info add-stakeholder" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                }
            }
        });
        add(edrreports, data_reports);

        var edrconsults = $('#edrconsults');
        edrconsults.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'name',
                displayKey: 'text',
                source: Stakeholder.ttAdapter(),
                templates: {
                    highlight: true,
                    empty: '<div class="empty-message text-info add-stakeholder" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                }
            }
        });
        add(edrconsults, data_consults);

        var edrliaises = $('#edrliaises');
        edrliaises.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'name',
                displayKey: 'text',
                source: Stakeholder.ttAdapter(),
                templates: {
                    empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                }
            }
        });
        add(edrliaises, data_liaises);

        var edrdelegate = $('#edrdelegate');
        edrdelegate.tagsinput({
            itemValue: 'value',
            itemText: 'text',
            typeaheadjs: {
                name: 'name',
                displayKey: 'text',
                source: Stakeholder.ttAdapter(),
                templates: {
                    empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
                },
            }
        });
        add(edrdelegate, data_delegate);

    });
    function add($elt, data){
        $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name});
        });
    }

    

</script>
<!-- /.blockJS -->