<p><?php $this->flashSession->output() ?></p>
<!-- <div class="wrapper"> -->
<div class="container-fluid">
    
    <!-- <div class="container"> -->
		
		<div class="row">
		<div class="col-md-12">
		<a href="<?=$this->url->get("stakeholder/create"); ?>" class="labelAdd btn btn-Primary pull-right"><i class="fa fa-plus"></i></a>

		</div>
		</div>
        <div class="row" style="margin-top: 50px">
            <div class="col-md-9">
                                
                <div class="fresh-table s-navShadow">
            
                  <table id="fresh-table" class="table">
                        <thead>
                            <th data-field="id">ID</th>
                        	<th data-field="name" data-sortable="true">Name</th>
                        	<!-- <th data-field="salary" data-sortable="true">Salary</th> -->
                        	<th data-field="country" data-sortable="true">Def</th>
                        	<th data-field="actions" data-formatter="" data-events="operateEvents">Manage Actions</th>
						</thead>
						<tbody>
                            <?php 
                                $i =1;
                                foreach($stake as $showStake) {  ?>
						    <tr>
                            	<td><?= $i ?></td>
                                <td><?=$showStake->name ?></td>
                                <td><?=$showStake->description ?></td>
                            	<td>

									<a onclick="confirm('Are you sure delete <?=$showStake->name?>?')?deleteResource('<?=$showStake->_id?>'):false;" class="btn btn-danger btn-xs pull-right labelDanger" role="button" style="margin-left: 3px;" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>&nbsp; 
                          			<a href="#" class="btn btn-primary btn-xs pull-right labelPrimary stakeedit" data-id="<?=$showStake->_id?>" role="button" data-toggle="tooltip"  data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>  
                          
								</td>
                            </tr>
                                    
                                <?php  $i++; } ?> 
						</tbody>
                       
                    </table>
                </div>
                
                
			</div>
			
			<div class="col-md-3">
            <!-- Sort -->
            <div class="card s-navShadow">
                <div class="header">
                    <h4 class="title">Sort</h4>
                </div>
                <div class="content">
                    <div class="form-group">
                        <!-- <label for="sel1">Select list (select one):</label> -->
                        <select class="form-control" id="sel1">
                            <option selected>List</option>
                            <option>Title</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- Filter -->
            <div class="card s-navShadow">
                <div class="header">
                    <h4 class="title">Filter</h4>
                </div>
                <div class="content">
                    <form action="#">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Project Name</label>
                                <input type="text" class="form-control" placeholder="Project Name" value="">
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-default pull-right" type="submit">Filter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        </div>
    <!-- </div> -->
</div>

<!-- </div> -->
