
<!-- <div class="wrapper"> -->
<div class="container-fluid">

    <!-- <div class="container"> -->
		
		<div class="row">
		<div class="col-md-12">
        <a href="<?=$this->url->get("resource/create"); ?>" class="labelAdd btn btn-Primary pull-right"><i class="fa fa-plus"></i></a>

		</div>
		</div>
        <div class="row" style="margin-top: 50px">
            <div class="col-md-9">
                                
                <div class="fresh-table s-navShadow">
                <!--    Available colors for the full background: full-color-blue, full-color-azure, full-color-green, full-color-red, full-color-orange                  
                        Available colors only for the toolbar: toolbar-color-blue, toolbar-color-azure, toolbar-color-green, toolbar-color-red, toolbar-color-orange
                -->
                
                    <div class="toolbar">
                        <button id="alertBtn" class="btn btn-default">Alert</button>
                    </div>
                    
                    <table id="fresh-table" class="table">
                        <thead>
                            <th data-field="id">Name</th>
                        	<th data-field="name" data-sortable="true">Aka</th>
                        	<th data-field="salary" data-sortable="true">Concern</th>
                        	<th data-field="country" data-sortable="true">Type</th>
                        	<th data-field="actions" data-formatter="operateFormatter" data-events="operateEvents">Actions</th>
						</thead>
						<tbody>
							<tr>
                            	<td>Cara Stevens</td>
                            	<td>-</td>
                            	<td>-</td>
                                <td> </td>
                                <td></td>
							</tr>

                            <tr>
                            	<td>Donna Snider</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>

                            <tr>
                            	<td>Finn Camacho</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>

                            <tr>
                            	<td>Hermione Butler</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Jennifer Acosta</td>
                            	<td>its alias name</td>
                            	<td>-</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Jonas Alexander</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Lael Greer</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Michael Bruce</td>
                            	<td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Serge Baldwin</td>
                            	<td>ASSOC</td>
                            	<td>its concern and motivation</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Shad Decker</td>
                            	<td>its alias name</td>
                            	<td>-</td>
                                <td> </td>
                                <td></td>
							</tr>
                            <tr>
                                <td>Zenaida Frank</td>
                                <td>its alias name</td>
                            	<td>its concern and motivation</td>
                                <td></td>
                                <td></td>
							</tr>
                            <tr>
                            	<td>Zorita Serrano</td>
                            	<td>its alias name	</td>
                            	<td>its concern and motivation	</td>
                                <td> </td>
                                <td></td>
							</tr>
							
						</tbody>
                       
                    </table>
                </div>
                
                
			</div>
			
			<div class="col-md-3">
            <!-- Sort -->
            <div class="card s-navShadow">
                <div class="header">
                    <h4 class="title">Sort</h4>
                </div>
                <div class="content">
                    <div class="form-group">
                        <!-- <label for="sel1">Select list (select one):</label> -->
                        <select class="form-control" id="sel1">
                            <option selected>List</option>
                            <option>Title</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- Filter -->
            <div class="card s-navShadow">
                <div class="header">
                    <h4 class="title">Filter</h4>
                </div>
                <div class="content">
                    <form action="#">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Project Name</label>
                                <input type="text" class="form-control" placeholder="Project Name" value="">
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-default pull-right" type="submit">Filter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        </div>
    <!-- </div> -->
</div>

</div>