<!-- <section class="Section Section--hero Section--for-work u-textCenter">
<div class="Section-content u-mb--large">
  <div class="Container">
    <h1 class="Section--for-work--headline">Bring DigitalOcean to work</h1>
    <p class="u-textLarge u-mb--large">Over 50,000 teams around the world rely on DigitalOcean<br class="u-hiddenDown@small"> to run their company's workloads.</p>
    <a href="https://cloud.digitalocean.com/registrations/new" class="Button Button--contrast Button--primary Button--space">Get Started</a>
  </div>
</div>
</section> -->

<body id="page-top">

  <!-- Navigation -->
  <header id="header" class="masthead">
    <div class="header-content">
      <div class="row">
        <div class="col-12 col-lg-6 col-md-12 col-sm-12 col-xs-12">
          <div id="carouselExampleIndicators" class="carousel slide h-100" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <center>
                  <div class="device-container">
                    <div class="device-mockup imac white" style="max-width: 100%;">
                      <div class="device">
                        <div class="screen">
                          <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                        </div>
                        <div class="button">
                        </div>
                      </div>
                    </div>
                  </div>
                </center>
              </div>

              <div class="carousel-item">
                <center>
                  <div class="device-container">
                    <div class="device-mockup mac white" style="max-width: 100%;">
                      <div class="device">
                        <div class="screen">
                          <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                        </div>
                        <div class="button">
                        </div>
                      </div>
                    </div>
                  </div>
                </center>
              </div>

              <div class="carousel-item">
                <center>
                  <div class="device-container">
                    <div class="device-mockup ipad white" style="max-width: 70%;">
                      <div class="device">
                        <div class="screen">
                          <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                        </div>
                        <div class="button">
                        </div>
                      </div>
                    </div>
                  </div>
                </center>
              </div>

              <div class="carousel-item">
                <center>
                  <div class="device-container">
                    <div class="device-mockup iphone6 white" style="max-width: 40%;">
                      <div class="device">
                        <div class="screen">
                          <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                        </div>
                        <div class="button">
                        </div>
                      </div>
                    </div>
                  </div>
                </center>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span> -->
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span> -->
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6 col-md-12 col-sm-12 col-xs-12 my-auto">
          <div class="header-content-inner">
            <h1 id="homeHeading">Stakeholder Modeling Language</h1>
            <hr>
            <p>Stakeholder Management is critical to successfully initiating and maintaining an architectural program.</p>
            <a class="btn btn-default btn-xl js-scroll-trigger" href="#about">Get About!</a>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">ABOUT US!</h2>
          <hr class="hr-black">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
          <p>Welcome to the leading company on the market! Our success is driven by the highest quality customer service. We can meet the requirements even of the whimsical clients; there are no complex tasks for us! Thanks for your choice!</p>
        </div>
        <div class="col-12 col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <h3 class="mb-3">Our history</h3>
          <div class="row">
            <div class="col-12">
              <p class="text-muted">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              </p>
              <p class="text-muted">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <h3 class="mb-3">Our services</h3>
          <div class="row">
            <div class="col-12">
              <div class="media">
                <div class="service-left pr-3">
                  <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
                </div>
                <div class="service-body">
                  <h5>Title Name</h5>
                  <p class="text-muted">
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-12">
              <div class="media">
                <div class="service-left pr-3">
                  <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
                </div>
                <div class="service-body">
                  <h5>Title Name</h5>
                  <p class="text-muted">
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="bg-dark bg-primary" id="feature">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">At Your Feature!</h2>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-diamond fa-stack-1x text-primary"></i>
            </span>
            <h3>Sturdy Templates</h3>
            <p>Our templates are updatedy.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-paper-plane fa-stack-1x text-primary"></i>
            </span>
            <h3>Ready to Ship</h3>
            <p>You can use this theme as is, or you can make changes!</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-newspaper-o fa-stack-1x text-primary"></i>
            </span>
            <h3>Up to Date</h3>
            <p>We update dependencies to keep things fresh.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-heart fa-stack-1x text-primary"></i>
            </span>
            <h3>Made with Love</h3>
            <p>You have to make your websites with love these days!</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-handshake-o fa-stack-1x text-primary"></i>
            </span>
            <h3>Sturdy Templates</h3>
            <p>Our templates are updated regularly so they don't break.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-address-book fa-stack-1x text-primary"></i>
            </span>
            <h3>Ready to Ship</h3>
            <p>You can use this theme as is, or you can make changes!</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-sitemap fa-stack-1x text-primary"></i>
            </span>
            <h3>Up to Date</h3>
            <p>We update dependencies to keep things fresh.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <span class="fa-stack fa-4x sr-icons">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-cubes fa-stack-1x text-primary"></i>
            </span>
            <h3>Made with Love</h3>
            <p>You have to make your websites with love these days!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="contact" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">Contact Me!</h2>
          <hr class="hr-black">
        </div>
      </div>
    </div>
    <div class="container mt-3">
      <div class="row">
        <div class="col-12 col-lg-6 col-md-6 map mb-4">
          <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"  src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15778.096214305084!2d99.89696836085206!3d8.64160485847068!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sth!2sth!4v1471851652192"></iframe>
        </div>
        <div class="col-12 col-lg-6 col-md-6 mx-auto text-center">
          <div class="row">
            <div class="col-12">
              <h2 class="section-heading">Let's Get In Touch!</h2>
              <hr class="primary">
              <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-6 text-center">
              <i class="fa fa-phone fa-3x sr-contact"></i>
              <p>123-456-6789</p>
            </div>
            <div class="col-lg-6 text-center">
              <i class="fa fa-envelope-o fa-3x sr-contact"></i>
              <p>
                <a href="mailto:your-email@your-domain.com">test@wu.ac.th.com</a>
              </p>
            </div>
            <div class="col-12">
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a style="color:#3B5998;" href="#">
                    <i class="fa fa-facebook fa-fw fa-3x"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a style="color:#1dcaff;" href="#">
                    <i class="fa fa-twitter fa-fw fa-3x"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a style="color:#d34836;" href="#">
                    <i class="fa fa-google-plus fa-fw fa-3x"></i>
                  </a>
                </li>
              </ul>
              <!-- <ul class="list-inline list-social">
                <li class="list-inline-item social-twitter">
                  <a href="#">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li class="list-inline-item social-facebook">
                  <a href="#">
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li class="list-inline-item social-google-plus">
                  <a href="#">
                    <i class="fa fa-google-plus"></i>
                  </a>
                </li>
              </ul> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
