<!-- <section class="Section Section--hero Section--for-work u-textCenter">
<div class="Section-content u-mb--large">
  <div class="Container">
    <h1 class="Section--for-work--headline">Bring DigitalOcean to work</h1>
    <p class="u-textLarge u-mb--large">Over 50,000 teams around the world rely on DigitalOcean<br class="u-hiddenDown@small"> to run their company's workloads.</p>
    <a href="https://cloud.digitalocean.com/registrations/new" class="Button Button--contrast Button--primary Button--space">Get Started</a>
  </div>
</div>
</section> -->
