<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-9">
            <div class="card s-navShadow">
               <div class="header">
                  <h4 class="title">Create Resource</h4>
               </div>
               <div class="content">
                  <form>
                     <div class="row">
                        <div class="col-md-12">
                           <div class="form-group">
                              <label>Resource Name</label>
                              <input type="text" class="form-control" placeholder="Resource Name...">
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-12">
                           <div class="form-group">
                              <label>description</label>
                              <textarea rows="5" class="form-control" placeholder="Here can be your description"></textarea>
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-12">
                           <div class="form-group">
                              <label>includes</label>
                              <input type="text" class="form-control" placeholder="Resource Name...">
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-6">
                           <div class="form-group">
                              <label>r Owner</label>
                              <input type="text" class="form-control" placeholder="Stakeholder name">
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="form-group">
                              <label>p Owner</label>
                              <input type="text" class="form-control" placeholder="Stakeholder name">
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-12">
                           <div class="form-group">
                              <label>Maintainer</label>
                              <input type="text" class="form-control" placeholder="Stakeholder Name...">
                           </div>
                        </div>
                     </div>
                     <button type="submit" class="btn btn-info btn-fill pull-right">Save Resource</button>
                     <div class="clearfix"></div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>