<?php
   echo $this->tag->form(
       [
         
           "autocomplete" => "off",
           "class" => "",
           "id" => "editResource"
       ]
   );
   ?>

    <?php 
         echo $this->tag->hiddenField(["idProject", "id" => "idProjectEdit" ]);
         echo $this->tag->hiddenField(["idResource", "id" => "idResourceEdit" ]);  
   ?>
<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                     <div class="header">
                        <h4 class="title">Create Resource</h4>
                     </div>
                     <div class="content">
                        <form>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Resource Name</label>
                                    <?php 
                                       echo $this->tag->textField(["editResName", "size" => 30, 
                                       "class" => "form-control", "id" => "editResName" , "placeholder"=>"Resource Name..."]) 
                                       ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>description</label>
                                    <?php 
                                       echo $this->tag->textArea(["editResDesCription", "class" => "form-control", 
                                        "id" => "editResDesCription" , "placeholder"=>"Here can be your description...","rows" => 3,]) 
                                       ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>includes</label>
                                    <?php 
                                       echo $this->tag->textField(["includes", "size" => 30, 
                                       "class" => "form-control", "id" => "Editincludes"]) 
                                       ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-6">
                                 <div class="form-group">
                                    <label>r Owner</label>
                                    <?php 
                                       echo $this->tag->textField(["rOwner", "size" => 30, 
                                       "class" => "form-control", "id" => "EditrOwner"]) 
                                       ?>
                                 </div>
                              </div>
                              <div class="col-md-6">
                                 <div class="form-group">
                                    <label>p Owner</label>
                                    <?php 
                                       echo $this->tag->textField(["pOwner", "size" => 30, 
                                       "class" => "form-control", "id" => "EditpOwner"]) 
                                       ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Maintainer</label>
                                    <?php 
                                       echo $this->tag->textField(["maintainer", "size" => 30, 
                                       "class" => "form-control", "id" => "Editmaintainer"]) 
                                       ?>
                                 </div>
                              </div>
                           </div>
                           <?php echo $this->tag->endForm(); ?>
                           <button type="submit" class="btn btn-info btn-fill pull-right"  id="saveEditResource">Save Resource</button>
                           <div class="clearfix"></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<!-- blockJS -->
<script src="<?php echo $this->url->get('public/modal/cloneModal.js');?>"></script>
<script src="<?php echo $this->url->get('public/jslif/tagResource.js');?>"></script>


<script>
      var stakeinput = '<?php echo json_encode($tagsStake); ?>';
      stakeinput = JSON.parse(stakeinput);
      stakeinput = createJSON(stakeinput);
      stakeinput = JSON.stringify(stakeinput);

      var data_rOwner = '<?php echo json_encode($rOwner); ?>';
      var data_pOwner = '<?php echo json_encode($pOwner); ?>';
      var data_maintainer = '<?php echo json_encode($maintainer); ?>';


      var resourceinput = '<?php echo json_encode($resourceTags); ?>';
      resourceinput = JSON.parse(resourceinput);
      resourceinput = createJSON(resourceinput);
      resourceinput = JSON.stringify(resourceinput);


      var data_includes = '<?php echo json_encode($includes); ?>';

      $(document).ready(function() {

            Stakeholder = new Bloodhound({
                  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
                  queryTokenizer: Bloodhound.tokenizers.whitespace,
                  local: JSON.parse(stakeinput)
            });

            Stakeholder.initialize();

            var EditrOwner = $('#EditrOwner');
            EditrOwner.tagsinput({
                  itemValue:'value',
                  itemText: 'text',
                  typeaheadjs:{
                        name : 'name',
                        displayKey: 'text',
                        source: Stakeholder.ttAdapter(),
                        templates: {
                              empty: '<div class="empty-message text-info"> No matches.</div>'

                        },
                  }

            })
            add(EditrOwner,data_rOwner);



      });

      function add($elt, data){
          $.each(JSON.parse(data), function(index ,data){   
            $elt.tagsinput('add', { "value": data._id.$id, "text": data.name});
          });
      }

      // function createJSON(data) {
      //       jsonObj = [];
      //       var i = 2;
      //       $.each(data, function (index, data) {

      //           item = {};
      //           item["value"] = data._id.$id;
      //           item["text"] = data.username;
      //           item["continent"] = "";
      //           i++;
      //           jsonObj.push(item);
      //       });

      //       return jsonObj;
      //   }
      
</script>
<!-- /.blockJS -->