<!-- <div class="wrapper"> -->
<div class="container-fluid">
   <!-- <div class="container"> -->
   <div class="row">
      <div class="col-md-12">
         <a href="<?=$this->url->get("resource/create"); ?>" class="labelAdd btn btn-Primary pull-right"><i class="fa fa-plus"></i></a>
      </div>
   </div>
   <div class="row" style="margin-top: 50px">
      <div class="col-md-9">
         <div class="fresh-table s-navShadow">
            <table id="fresh-table" class="table">
               <thead>
                  <th data-field="id">ID</th>
                  <th data-field="name" data-sortable="true">Name</th>
                  <!-- <th data-field="salary" data-sortable="true">Salary</th> -->
                  <th data-field="country" data-sortable="true">Def</th>
                  <th data-field="actions" data-formatter="" data-events="operateEvents">Manage Actions</th>
               </thead>
               <tbody>
                  <?php 
                     $i =1;
                     foreach($resource->items as $key => $showRes) {  ?>
                  <tr>
                     <td><?= $i ?></td>
                     <td>
                           <h6 style="color: #747474"><?=$showRes->name ?></h6>
                
                     </td>
                     <td><?=$showRes->description ?></td>
                     <td>
                        <a onclick="confirm('Are you sure delete <?=$showRes->name?>?')?deleteResource('<?=$showRes->_id?>'):false;" class="btn btn-danger btn-xs pull-right labelDanger" role="button" style="margin-left: 3px;" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>&nbsp; 
                        <a href="#" class="btn btn-primary btn-xs pull-right labelPrimary resEdit" data-id="<?=$showRes->_id?>" role="button" data-toggle="tooltip"  data-placement="top" title="Edit"><i class="fa fa-edit"></i></a> 
                        <a class="showDetailRes btn btn-xs pull-right"  onclick="cloneModalDetailRes('<?=$showRes->_id?>')" role="button" style="margin-right: 3px;" data-toggle="tooltip" data-placement="top" title="Show"><i class="fa fa-eye"></i></a>&nbsp; 

                     </td>
                  </tr>
                  <?php  $i++; } ?> 
               </tbody>
            </table>
         </div>
      </div>
      <form action="<?=$this->url->get("resource/index"); ?>" method="POST">
        <div class="col-md-3">
         <!-- Sort -->
         <div class="card s-navShadow">
            <div class="header">
               <h4 class="title">Sort</h4>
            </div>
            <div class="content">
               <div class="form-group">
               <?php 
               echo $this->tag->select(
                   [
                           'sortBy',
                           $arrSortBy,
                           'value' => $sortBy,
                           'class' => 'form-control',
                           'id' => 'sel1',
                           'onchange' => 'this.form.submit()'
                   ]
               );
               ?>

                  
               </div>
            </div>
         </div>
         <!-- Filter -->
         <div class="card s-navShadow">
            <div class="header">
               <h4 class="title">Filter</h4>
            </div>
            <div class="content">
                  <div class="form-group">
                     <div class="form-group">
                        <label>Resource Name</label>
                        <input type="text" class="form-control"  name="filter" value="<?=$filter?>">
                     </div>
                  </div>
                  <div class="footer text-right">
                     <button class="btn btn-default" type="submit">Filter</button>
                  </div>
               </div>
         </div>
        </div>
      </form>
   </div>
   <?php echo $resource->widgetPagination; ?>

   <!-- </div> -->
</div>
<!-- </div> -->
<div class="modal showRes" id="showRes" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content card">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Resource Details</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <div class="row">
                  <div class="col-md-6">
                     <label>Resource name</label>
                     <h5 id="showResName"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <label>Description</label>
                     <h5 id="showResDescription"></h5>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-12">
                     <label>Includes</label>
                     <div id="showResInclude"></div>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-6">
                     <label>R Owner</label>
                     <div id="showResRowner"></div>
                  </div>
                  <div class="col-md-6">
                     <label>P Owner</label>
                     <div id="showResPowner"></div>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-12">
                     <label>Maintainer</label>
                     <div id="showResMaintainer"></div>
                  </div>
               </div>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- blockJS -->
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script>
   function deleteResource(id){
       var idresource = id;
   
       $.post(baseUrl+"resource/deleteResource",{
           idResource : idresource
       }, function(data){
          window.location.href = baseUrl+"resource";
       },  "json");
      
   }
</script>
<!-- /.blockJS -->