<p></p>
<ol class="breadcrumb inline-flex">
   <li class="breadcrumb-item">
      <a href="<?=$this->url->get("project/index"); ?>">Project</a>
   </li>
   <li class="breadcrumb-item active">
      <a>Create</a>
   </li>
</ol>
<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                     <div class="header">
                        <h4 class="title">Create Project</h4>
                     </div>
                     <div class="content">
                        <form id="createProject-form">
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Project Name <span class="red-star" style="font-size: 14px"> *</span></label>
                                    <input type="text" class="form-control" name="projectname" id="projectname" placeholder="Project Name">
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Description</label>
                                    <textarea id="description" class="form-control" name="description" id="description" rows="3"></textarea>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Permission</label>
                                    <div>
                                       <?php 
                                          echo $this->tag->textField(["permission", "size" => 30, 
                                          "class" => "form-control", "id" => "permission" ]) 
                                          ?> 
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button type="button" class="btn btn-info btn-fill pull-right" id="saveproject">Save Project</button>
                           <div class=""></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>