
<div class="formadd hero card card-pad">


<div class="container">
                                    <!-- container -->
                                    <form>
                                        <div class="form-group row">
                                            <label for="project" class="col-sm-2 col-form-label">Project Name</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control" id="projectname" placeholder="Project Name">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="project" class="col-sm-2 col-form-label">Description</label>
                                            <div class="col-sm-6">
                                                <textarea id="description" class="form-control" id="description" rows="3"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="project" class="col-sm-2 col-form-label">tag</label>
                                            <div class="col-sm-6">
                                                <input type="text" id="tag" class="form-control" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-sm-2 col-form-label">
                                                Stakeholder
                                            </label>
                                            <div class="col-sm-6">
                                                <div class="input-group">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control" id="Stakeholder" aria-label="Text input with dropdown button">
                                                    </div>
                                                    <div class="float-right pl-3">
                                                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal2">
                                                            <i class="fa fa-fw fa-plus"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="offset-sm-2 col-sm-10">
                                                <button type="submit" class="btn btn-primary">Save</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
</div>
<!-- /.container-->
</div>
