<div class="formadd hero card card-pad">


    <div class="container">
        <!-- container -->
        <form>
            <div class="form-group row">
                <label for="project" class="col-sm-2 col-form-label">Project Name</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" name="projectname" id="projectname" placeholder="Project Name">
                </div>
            </div>
            <div class="form-group row">
                <label for="project" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-6">
                    <textarea id="description" class="form-control" name="description" id="description" rows="3"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">
                    Permission
                </label>
                <div class="col-sm-6">
                    
                        
                            <?php 
                                echo $this->tag->textField(["permission", "size" => 30, 
                                "class" => "form-control", "id" => "permission" ]) 
                            ?>
                       

                    
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
