<p></p>
<ol class="breadcrumb inline-flex">
   <li class="breadcrumb-item">
      <a href="<?=$this->url->get("project/index"); ?>">Project</a>
   </li>
   <li class="breadcrumb-item active">
      <a>Edit</a>
   </li>
</ol>

<input type="hidden" name="idproject" id="idproject" value="<?php echo $pro->_id ?>"/>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Edit Project</h4>
                    </div>
                    <div class="content">
                        <form id="editProject-form">
                            <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                    
                                        <label>Project Name<span class="red-star" style="font-size: 14px"> *</span></label>

                                        <?php 
                                            echo $this->tag->textField(["edprojectname", "size" => 30, 
                                            "class" => "form-control", "id" => "edprojectname" , "placeholder"=>"Project Name"]) 
                                        ?>
                                    </div>
                                    </div>
                                    </div>
                                   <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                        <label>Description</label>

                                        <?php 
                                            echo $this->tag->textArea(["eddescription", "rows" => 3, 
                                            "class" => "form-control", "id" => "eddescription" , "placeholder"=>"Description"]) 
                                        ?>
                                    </div>
                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                        <label>Permission</label>
                                        
                                            <?php 
                                                echo $this->tag->textField(["edpermission", "size" => 30, 
                                                "class" => "form-control", "id" => "edpermission" ]) 
                                            ?>
                                        </div>
                                    </div>
                                    </div>
                                    <button type="button" class="btn btn-info btn-fill pull-right" id="editproject">Save</button>
                                
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- blockJS -->
<script>

        var user = '<?php echo json_encode($user); ?>';
        
        user = JSON.parse(user);
        user = createJSON(user);
        user = JSON.stringify(user);    
        var data_permission = '<?php echo json_encode($permission); ?>';
    $(document).ready(function () {
            var users = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: JSON.parse(user)
            });

            
            users.initialize();

            var Edpermission = $('#edpermission');
                Edpermission.tagsinput({
                itemValue: 'value',
                itemText: 'text',
                typeaheadjs: {
                    username: 'username',
                    displayKey: 'text',
                    source: users.ttAdapter(),
                    templates: {
                        empty: '<div class="empty-message text-info"> No matches.</div>'
                    }
                }
            });
            add(Edpermission, data_permission);
    });
        function add($elt, data){
        $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.username, "continent": ""});
        });
        } 


        function createJSON(data) {
            jsonObj = [];
            var i = 2;
            $.each(data, function (index, data) {

                item = {};
                item["value"] = data._id.$id;
                item["text"] = data.username;
                item["continent"] = "";
                i++;
                jsonObj.push(item);
            });

            return jsonObj;
        }
    
</script>
<!-- /.blockJS -->