<!-- random color just for fun -->
<?php 
   $co = array('blue', 'green', 'orange', 'pink', 'purple', 'red', 'teal', 'yellow' );
   $i = rand(0, count($co)-1);
   $selectedCo = "$co[$i]"; 
   ?>
<!-- new project card -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="header">
                    <h4 class="title">Projects</h4>
                    <!-- <p class="category">All Project is here</p> -->
                </div>
                <div class="content books">
                    <!-- card -->
                    <ul class="row resources">
                        <li class="col-md-4 resource--add well">
                            <div class="resource__add-icon">
                                <a href="<?= $this->url->get(" project/create "); ?>">
                                    <svg class="add" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
                                        <circle cx="30" cy="30" r="30" />
                                        <polygon fill="#FFFFFF" points="44.677,27.404 44.677,33.404 32.677,33.404 32.677,45.404 26.677,45.404 26.677,33.404 14.677,33.404 14.677,27.404 26.677,27.404 26.677,15.404 32.677,15.404 32.677,27.404 "
                                        />
                                    </svg>
                                </a>
                            </div>
                        </li>
                        <?php
                        foreach ($create as $key => $pro) {
                    ?>
                            <?php echo "<li class='col-md-4 resource--talks well ".$selectedCo."' >"; ?>
                            <div class="header">
                                <h4 class="title">Edit Profile</h4>
                            </div>
                            <div class="content">
                                <p>
                                    <?=$pro->description?>
                                </p>
                                <div class="footer">
                                    <hr>
                                    <div class="pull-right">
                                        <a href="#" data-id="<?=$pro->_id?>" class="projectedit" rel="tooltip" title="" class="btn btn-info btn-simple btn-sm" data-original-title="Edit">
                                                <i class="pe-7s-edit"></i>
                                        </a>
                                        <a href="#" rel="tooltip" title="" class="btn btn-danger btn-simple btn-sm" data-original-title="Remove">
                                                <i class="pe-7s-trash"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                            <?php 
                                 $i = rand(0, count($co)-1);
                                 $selectedCo = "$co[$i]"; 
                                 ?>
                            <?php } ?>
                            <!-- permis -->
                            <?php 
                                 $i = rand(0, count($co)-1);
                                 $selectedCo = "$co[$i]"; 
                                 ?>
                            <?php
                                 foreach ($permis as $key => $per) {
                                 ?>
                                <!-- <li class="resource--book"> -->
                                <?php echo "<li class='resource--book ".$selectedCo."' >"; ?>
                                <a href="<?=$this->url->get(" project/task/ ".$pro->_id); ?>" class="resource__link">
                                    <h1 class="resource__title">
                                        <?=$pro->name?>
                                    </h1>
                                    <p class="resource__summary">
                                        <?=$pro->description?>
                                    </p>
                                </a>
                                </li>
                                <?php } ?>
                    </ul>
                    <?php 
                    $i = rand(0, count($co)-1);
                    $selectedCo = "$co[$i]"; 
                ?>
                    </ul>


                </div>
            </div>

        </div>
        <div class="col-md-3">
            <!-- Sort -->
            <div class="card">
                <div class="header">
                    <h4 class="title">Sort</h4>
                </div>
                <div class="content">
                    <div class="form-group">
                        <!-- <label for="sel1">Select list (select one):</label> -->
                        <select class="form-control" id="sel1">
                            <option selected>List</option>
                            <option>Title</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- Filter -->
            <div class="card">
                <div class="header">
                    <h4 class="title">Filter</h4>
                </div>
                <div class="content">
                    <form action="#">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Project Name</label>
                                <input type="text" class="form-control" placeholder="Project Name" value="">
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-default pull-right" type="submit">Filter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- blockJS -->
<script>
    $(document).ready(function () {
        $('.projectedit').click(function () {
            var projectid = $(this).data('id');
            // $(this).attr('data-id');
            $.redirect("edit", {
                id: projectid
            });
        });
    });

    console.log(true);
</script>
<!-- /.blockJS -->