<?php $this->flashSession->output() ;
   echo $this->session->get('login');
   ?>
<div class="ui grid">
    <div class="ten wide column">
        <div class="ui cards">
            <?php
            foreach ($project as $key => $pro) {
        ?>

                <div class="ui raised link card">
                    <div class="content">
                        <div class="header">
                            <a href="<?=$this->url->get("project/task/".$pro->_id); ?>">
                                <?=$pro->name?>
                            </a>
                        </div>
                        <div class="description">
                            <?=$pro->description?>
                        </div>
                    </div>
                    <!-- <a href="<?=$this->url->get("project/edit/"); ?>"> -->

                    <div class="ui bottom attached button">

                        <div class="ui simple dropdown item">
                            Manage Project
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a class="item" href="<?=$this->url->get("project/edit/".$pro->_id); ?>">
                                    <i class="wizard icon"></i>Edit</a>
                                <a class="item" href="">
                                    <i class="remove icon"></i>Delete</a>
                            </div>
                        </div>

                    </div>

                </div>
                <!-- </a> -->
                <?php } ?>
        </div>


        <!-- This one have dropdown and link but i'm query to make sure it's alright  -->


    </div>

    <div class="five wide column">
        <div class="ui raised segments">
            <!-- <div class="ui segment">
            <p>Top</p>
         </div> -->

            <div class="ui segment very padded">
                <h2 class="ui header">

                    <div class="content">
                        Search Project
                        <div class="sub header">Search your projects</div>
                    </div>
                </h2>
                <div class="ui search">
                    <div class="ui icon input">
                        <input class="prompt" type="text" placeholder="project name...">
                        <i class="search icon"></i>
                    </div>
                    <div class="results"></div>
                </div>

            </div>

            <div class="ui segment very padded">
                <h2 class="ui header">

                    <div class="content">
                        Sort Project
                        <div class="sub header">sort your project</div>
                    </div>
                </h2>
                <select class="ui dropdown">
                    <option value="">Sort</option>
                    <option value="1">List</option>
                    <option value="0">Title</option>
                </select>

            </div>
        </div>
    </div>
</div>