<!-- random color just for fun -->
<?php 
   $co = array('blue', 'green', 'orange', 'pink', 'purple', 'red', 'teal', 'yellow' );
   $i = rand(0, count($co)-1);
   $selectedCo = "$co[$i]"; 
   ?>
<!-- new project card -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <section class="books">
                <h2 class="section__title">Projects</h2>
                <p class="section__summary">All Project is here</p>
                <ul class="resources">
                    <li class="resource--add">
                        <a href="<?=$this->url->get(" project/create "); ?>">

                            <div class="resource__add-icon">
                                <svg class="add" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
                                    <circle cx="30" cy="30" r="30" />
                                    <polygon fill="#FFFFFF" points="44.677,27.404 44.677,33.404 32.677,33.404 32.677,45.404 26.677,45.404 26.677,33.404 14.677,33.404 14.677,27.404 26.677,27.404 26.677,15.404 32.677,15.404 32.677,27.404 "
                                    />
                                </svg>
                            </div>
                        </a>
                    </li>
                    <?php
                     foreach ($create as $key => $pro) {
                     ?>
                        <!-- <li class="resource--book"> -->
                        <?php echo "<li class='resource--book ".$selectedCo."' >"; ?>
                        <a href="<?=$this->url->get(" project/task/ ".$pro->_id); ?>" class="resource__link">
                            <h1 class="resource__title">
                                <?=$pro->name?>
                            </h1>
                            <p class="resource__summary">
                                <?=$pro->description?>
                            </p>
                        </a>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="pe-7s-tools" style="font-weight: 900"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#" data-id="<?=$pro->_id?>" class="projectedit">
                                        <i class="pe-7s-pen"></i> Edit</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="pe-7s-trash"></i> Delete</a>
                                </li>

                            </ul>
                        </div>
                        </li>
                        <?php 
                     $i = rand(0, count($co)-1);
                     $selectedCo = "$co[$i]"; 
                     ?>
                        <?php } ?>
                        <!-- permis -->
                        <?php 
                     $i = rand(0, count($co)-1);
                     $selectedCo = "$co[$i]"; 
                     ?>
                        <?php
                     foreach ($permis as $key => $per) {
                     ?>
                            <!-- <li class="resource--book"> -->
                            <?php echo "<li class='resource--book ".$selectedCo."' >"; ?>
                            <a href="<?=$this->url->get(" project/task/ ".$pro->_id); ?>" class="resource__link">
                                <h1 class="resource__title">
                                    <?=$pro->name?>
                                </h1>
                                <p class="resource__summary">
                                    <?=$pro->description?>
                                </p>
                            </a>
                            </li>
                            <?php } ?>
                </ul>
            </section>
            <?php 
               $i = rand(0, count($co)-1);
               $selectedCo = "$co[$i]"; 
            ?>
        </div>
       
    </div>
</div>

<!-- blockJS -->
<script>
    $(document).ready(function () {
        $('.projectedit').click(function () {
            var projectid = $(this).data('id');
            // $(this).attr('data-id');
            $.redirect("edit", {
                id: projectid
            });
        });
    });
</script>
<!-- /.blockJS -->