<p></p>
<ol class="breadcrumb inline-flex">
    <li class="breadcrumb-item">
        <a href="<?=$this->url->get("project/index"); ?>">Project</a>
    </li>
    <li class="breadcrumb-item">
        <a href="<?=$this->url->get("task/index"); ?>">Task</a>
    </li>
    <li class="breadcrumb-item active">
            <a>Edit</a>
    </li>
</ol>
<!-- new -->
<h2 class="headform textCenter">Edit Task</h2>
<?php
   echo $this->tag->form(
       [
           "autocomplete" => "off",
           "id" => "editTask-form"
       ]
   );
?>
<?php 
echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]);
echo $this->tag->hiddenField(["idTask", "id" => "EdidTask" ]);
?>
 <div class="content">
  <div class="container-fluid">
     <div class="row">
        <div class="col-md-12">
           <div class="card s-navShadow">
              <div class="row">
                 <div class="col-md-8 col-md-offset-2">
                    <div class="header">
                       <h4 class="title">Edit Task</h4>
                    </div>
                    <div class="content">
                       <form>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                                   <?php 
                                      echo $this->tag->textField(["taskname", "size" => 30, 
                                      "class" => "form-control", "id" => "Edname"]) 
                                  ?>
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>IsA</label>
                                   <?php 
                                    echo $this->tag->textField(["isA", "size" => 30, 
                                    "class" => "form-control", "id" => "EdisA" ]) 
                                  ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-12">
                                <div class="form-group">
                                   <label>Description</label>
                                   <?php 
                                      echo $this->tag->textArea(["task_Description", "class" => "form-control", 
                                      "id" => "EdDescription","rows" => 3,]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-8">
                                <div class="form-group">
                                   <label>Includes Tasks</label>
                                  <?php 
                                      echo $this->tag->textField(["includes", "size" => 30, 
                                      "class" => "form-control", "id" => "Edincludes"]) 
                                  ?>
                                       <i class="fa fa-plus iconInput createTaskIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>as IsState</label>
                                    <?php 
                                        echo $this->tag->selectStatic(["asIsState", "class" => "form-control", 
                                        "id" => "EdasIsState" 
                                          ,[
                                              "E" => "EXIST",
                                              "N" => "NEXIST",
                                          ]
                                        ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Owner</label>
                                   <?php 
                                      echo $this->tag->textField(["owner", "size" => 30, 
                                      "class" => "form-control", "id" => "Edowner" ]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Collaburator</label>
                                   <?php 
                                      echo $this->tag->textField(["collaburator", "size" => 30, 
                                      "class" => "form-control", "id" => "Edcollaburator" ]) 
                                  ?>
                                  <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>Regulator</label>
                                    <?php 
                                      echo $this->tag->textField(["regulator", "size" => 30, 
                                      "class" => "form-control", "id" => "Edregulator"]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-8">
                                <div class="form-group">
                                   <label>Resource used</label>
                                   <?php 
                                      echo $this->tag->textField(["uses", "size" => 30, 
                                      "class" => "form-control", "id" => "Eduses" ]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createResourceIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-4">
                                <div class="form-group">
                                   <label>to Be State</label>
                                    <?php 
                                        echo $this->tag->selectStatic(["toBeState", "class" => "form-control", 
                                        "id" => "EdtoBeState" 
                                          ,[
                                              "E" => "EXIST",
                                              "N" => "NEXIST",
                                              "A" => "ADEPTED",
                                          ]
                                        ]) 
                                    ?>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-12">
                                <div class="form-group">
                                   <label>Resource Produces</label>
                                   <?php 
                                        echo $this->tag->textField(["produces", "size" => 30, 
                                        "class" => "form-control", "id" => "Edproduces" ]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createResourceIcon"></i>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>owner To Be</label>
                                   <?php 
                                      echo $this->tag->textField(["ownerToBe", "size" => 30, 
                                      "class" => "form-control", "id" => "EdownerToBe"]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>collaborator To Be</label>
                                   <?php 
                                      echo $this->tag->textField(["collaboratorToBe", "size" => 30, 
                                      "class" => "form-control", "id" => "EdcollaboratorToBe" ]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createStakeholderIcon"></i>
                                </div>
                             </div>
                          </div>
                          <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>Resource to used</label>
                                   <?php 
                                      echo $this->tag->textField(["toUse", "size" => 30, 
                                      "class" => "form-control", "id" => "EdtoUse"]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createResourceIcon"></i>
                                </div>
                             </div>
                             <div class="col-md-6">
                                <div class="form-group">
                                   <label>Resource to Produces</label>
                                   <?php 
                                      echo $this->tag->textField(["toProduce", "size" => 30, 
                                      "class" => "form-control", "id" => "EdtoProduce"]) 
                                    ?>
                                    <i class="fa fa-plus iconInput createResourceIcon"></i>
                                </div>
                             </div>
                          </div>
                          <?php echo $this->tag->endForm(); ?>
                          <button type="button" class="btn btn-info btn-fill pull-right" id="editTask">Save</button>
                          <div class="clearfix"></div>
                       </form>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>
</div>


<!-- blockJS -->

<script>
    $(".createTaskIcon").click(function(){
        cloneModalTask($('#createTask'));
    });

    $(".createResourceIcon").click(function(){
        cloneModalResource($('#createResource'));
    });

    $(".createStakeholderIcon").click(function(){
        cloneModalStakeholder($('#createStakeholder'));
    });
</script>
<script>
    questionMark($('#Edincludes'));
    questionMark($('#Edowner'));
    questionMark($('#Edcollaburator'));
    questionMark($('#Edregulator'));
    questionMark($('#Eduses'));
    questionMark($('#Edproduces'));
    questionMark($('#EdownerToBe'));
    questionMark($('#EdcollaboratorToBe'));
    questionMark($('#EdtoUse'));
    questionMark($('#EdtoProduce'));
</script>
<script>
    var taskinput = '<?php echo json_encode($taskTags); ?>';
    taskinput = JSON.parse(taskinput);
    taskinput = createJSON(taskinput);
    taskinput = JSON.stringify(taskinput);

    var data_includes = '<?php echo json_encode($includes); ?>';


    var stakeinput = '<?php echo json_encode($tagsStake); ?>';
    stakeinput = JSON.parse(stakeinput);
    stakeinput = createJSON(stakeinput);
    stakeinput = JSON.stringify(stakeinput);

    var data_owner = '<?php echo json_encode($owner); ?>';
    var data_collaburator = '<?php echo json_encode($collaburator); ?>';
    var data_regulator = '<?php echo json_encode($regulator); ?>';
    var data_ownerTobe = '<?php echo json_encode($ownerTobe); ?>';
    var data_collaboratorTobe = '<?php echo json_encode($collaboratorTobe); ?>';

             
    var resourceinput = '<?php echo json_encode($resourceTags); ?>';
    resourceinput = JSON.parse(resourceinput);
    resourceinput = createJSON(resourceinput);
    resourceinput = JSON.stringify(resourceinput);

    var data_uses = '<?php echo json_encode($uses); ?>';
    var data_produces = '<?php echo json_encode($produces); ?>';
    var data_toUse = '<?php echo json_encode($toUse); ?>';
    var data_toProduces = '<?php echo json_encode($toProduce); ?>';

  $(document).ready(function(){

    Tasks_Edit = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: JSON.parse(taskinput)
    });
    Tasks_Edit.initialize();
    
    var Edincludes = $('#Edincludes');
    Edincludes.tagsinput({
        itemValue: 'value',
        itemText: 'text',
        typeaheadjs: {
            name: 'name',
            displayKey: 'text',
            source: Tasks_Edit.ttAdapter(),
            templates: {
                empty: '<div class="empty-message text-info" onclick="cloneModalTask($(\'#createTask\'))"> No matches.</div>'
            },
        }
    });
    add(Edincludes, data_includes);


    Stakeholder_Edit = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: JSON.parse(stakeinput)
    });
  
    Stakeholder_Edit.initialize();

    var EdownerToBe = $('#EdownerToBe');
    EdownerToBe.tagsinput({
        itemValue: 'value',
        itemText: 'text',
        typeaheadjs: {
            name: 'name',
            displayKey: 'text',
            source: Stakeholder_Edit.ttAdapter(),
            templates: {
                empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
            },
        }
    });
    add(EdownerToBe, data_ownerTobe);


    var Edowner = $('#Edowner');
    Edowner.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edowner, data_owner);


    var Edcollaburator = $('#Edcollaburator');
    Edcollaburator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edcollaburator, data_collaburator);


    var Edregulator = $('#Edregulator');
    Edregulator.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(Edregulator, data_regulator);
   

    var EdcollaboratorToBe = $('#EdcollaboratorToBe');
    EdcollaboratorToBe.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Stakeholder_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalStakeholder($(\'#createStakeholder\'))"> No matches.</div>'
        },
      }
    });
    add(EdcollaboratorToBe, data_collaboratorTobe);


   Resource_Edit = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(resourceinput)
    });
    Resource_Edit.initialize();

    var Eduses = $('#Eduses');
    Eduses.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(Eduses, data_uses);


    var Edproduces = $('#Edproduces');
    Edproduces.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(Edproduces, data_produces);


    var EdtoUse = $('#EdtoUse');
    EdtoUse.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(EdtoUse, data_toUse);
   

    var EdtoProduce = $('#EdtoProduce');
    EdtoProduce.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Resource_Edit.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalResource($(\'#createResource\'))"> No matches.</div>'
        },
      }
    });
    add(EdtoProduce, data_toProduces);

   
});


  function add($elt, data){
    $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name});
    });
  }
</script>

<!-- /.blockJS -->