<p></p>
<ol class="breadcrumb inline-flex">
        <li class="breadcrumb-item">
            <a href="<?=$this->url->get("project/index"); ?>">Project</a>
        </li>
        <li class="breadcrumb-item">
            <a href="<?=$this->url->get("collaborationSetting/index"); ?>">Collaboration Setting</a>
        </li>
        <li class="breadcrumb-item active">
              <a>Create</a>
        </li>
</ol>
<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                     <div class="header">
                        <h4 class="title">Create Collaboration Setting</h4>
                     </div>
                     <div class="content">
                        <form id="createCollaboration-form">
                        <?php 
                            echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]) 
                        ?>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>CollaborationSetting Name <span class="red-star" style="font-size: 14px"> *</span></label>
                                    <input type="text" class="form-control" name="CollaborationSettingName" id="CollaborationSettingName" placeholder="Project Name">
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Description</label>
                                    <?php 
                                        echo $this->tag->textArea(["DescriptionColla", "rows" => 3, 
                                        "class" => "form-control", "id" => "DescriptionColla"]) 
                                    ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>include</label>
                                    <div>
                                       <?php 
                                          echo $this->tag->textField(["include", "size" => 30, 
                                          "class" => "form-control", "id" => "includeColla" ]) 
                                          ?> 
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button type="button" class="btn btn-info btn-fill pull-right" id="saveColla">Save</button>
                           <div class=""></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>


<!-- blockJS -->
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script src="<?php echo $this->url->get('/public/jslif/tagCollaboration.js');?>"></script>
<script>
      questionMark($('#includeColla'));
</script>
<!-- /.blockJS -->