<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                     <div class="header">
                        <h4 class="title">Create Collaboration Setting</h4>
                     </div>
                     <div class="content">
                        <form id="createCollaboration-form">
                        <?php 
                            echo $this->tag->hiddenField(["idProject", "id" => "idProject" ]) 
                        ?>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>CollaborationSetting Name <span class="red-star" style="font-size: 14px"> *</span></label>
                                    <input type="text" class="form-control" name="CollaborationSettingName" id="CollaborationSettingName" placeholder="Project Name">
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Description</label>
                                    <?php 
                                        echo $this->tag->textArea(["DescriptionColla", "rows" => 3, 
                                        "class" => "form-control", "id" => "DescriptionColla"]) 
                                    ?>
                                 </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>include</label>
                                    <div>
                                       <?php 
                                          echo $this->tag->textField(["include", "size" => 30, 
                                          "class" => "form-control", "id" => "includeColla" ]) 
                                          ?> 
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button type="submit" class="btn btn-info btn-fill pull-right" id="saveColla">Save</button>
                           <div class=""></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="modal createTask" id="createTask" role="dialog">
      <div class="modal-dialog">
         <!-- Modal content-->
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title">New Task</h4>
            </div>
            <div class="modal-body">
               <div class="content">
                  <form>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                              <input type="hidden" name="idProjectmodalTask" value="<?=$idProject?>" id="idProjectmodalTask">
                                 <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                                 <?php 
                                    echo $this->tag->textField(["Modaltaskname", "size" => 30, 
                                    "class" => "form-control", "id" => "Modaltaskname" , ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>IsA</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalIsATask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalIsATask" ,]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>Description</label>
                                 <?php 
                                    echo $this->tag->textArea(["ModalDescriptionTask", "class" => "form-control", 
                                     "id" => "ModalDescriptionTask" ,"rows" => 3,]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-8">
                              <div class="form-group">
                                 <label>Includes</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalincludesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalincludesTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>as IsState</label>
                                 <?php 
                                    echo $this->tag->selectStatic(["ModalasIsStateTask", "class" => "form-control", 
                                    "id" => "ModalasIsStateTask" 
                                    ,[
                                        "E" => "EXIST",
                                        "N" => "NEXIST",
                                    ]
                                    ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Owner</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalOwnerTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalOwnerTask" ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Collaburator</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalCollaburatorTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalCollaburatorTask" ]) 
                                    ?>  
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>Regulator</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalRegulatorTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalregulatorTask"]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-8">
                              <div class="form-group">
                                 <label>Uses</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalUsesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalUsesTask" ]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-4">
                              <div class="form-group">
                                 <label>to Be State</label>
                                 <?php 
                                    echo $this->tag->selectStatic(["ModalToBeStateTask", "class" => "form-control", 
                                    "id" => "ModalToBeStateTask" 
                                    ,[
                                        "E" => "EXIST",
                                        "N" => "NEXIST",
                                        "A" => "ADEPTED",
                                    ]
                                    ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-12">
                              <div class="form-group">
                                 <label>Produces</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalProducesTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalProducesTask" ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>owner To Be</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalOwnerToBeTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalOwnerToBeTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>collaborator To Be</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalCollaboratorToBeTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalCollaboratorToBeTask" ]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>toUse</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalToUseTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalToUseTask"]) 
                                    ?>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group">
                                 <label>toProduce</label>
                                 <?php 
                                    echo $this->tag->textField(["ModalToProduceTask", "size" => 30, 
                                    "class" => "form-control", "id" => "ModalToProduceTask"]) 
                                    ?>
                              </div>
                           </div>
                        </div>
                     </form>
               </div>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-info" id="saveTaskformModal">Save</button>
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
         </div>
      </div>
   </div>
<!-- blockJS -->
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script src="<?php echo $this->url->get('/public/jslif/tagCollaboration.js');?>"></script>
<script>
      questionMark($('#includeColla'));
</script>
<!-- /.blockJS -->