<ol class="breadcrumb inline-flex">
        <li class="breadcrumb-item">
            <a href="<?=$this->url->get("project/index"); ?>">Project</a>
        </li>
        <li class="breadcrumb-item">
            <a href="<?=$this->url->get("collaborationSetting/index"); ?>">Collaboration Setting</a>
        </li>
        <li class="breadcrumb-item">
              <a>Edit</a>
        </li>
</ol>
<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                     <div class="header">
                        <h4 class="title">Create Project</h4>
                     </div>
                     <div class="content">
                        <form id="editCollaboration-form">
                        <?php 
                            echo $this->tag->hiddenField (["EdIdProject", "id" => "EdIdProject" ]);
                            echo $this->tag->hiddenField (["EdId", "id" => "EdId" ]) 
                        ?>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>CollaborationSetting Name <span class="red-star" style="font-size: 14px"> *</span></label>
                                    <?php 
                                        echo $this->tag->textField(["EdCollaborationSettingName", "size" => 30, 
                                        "class" => "form-control", "id" => "EdCollaborationSettingName"]) 
                                    ?>
                                </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Description</label>
                                    <?php 
                                        echo $this->tag->textArea(["EdDescription", "rows" => 3, 
                                        "class" => "form-control", "id" => "EdDescription"]) 
                                    ?>
                                </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>include</label>
                                    <div>
                                       <?php 
                                          echo $this->tag->textField(["EdInclude", "size" => 30, 
                                          "class" => "form-control", "id" => "EdInclude" ]) 
                                          ?> 
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button type="button" class="btn btn-info btn-fill pull-right" id="EditColla">Save</button>
                           <div class=""></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<!-- blockJS -->

<script>
       
</script>         
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script src="<?php echo $this->url->get('/public/jslif/tagCollaboration.js');?>"></script>
<script>
    questionMark($('#EdInclude'));
</script>
<script>
      var idproject = '<?php echo $idProject; ?>';
      $.post(baseUrl+"task/findResource",{
          project : idproject
      }, function(data){
          var auto = createJSON(data);
          var n = createString(auto);
              Resource = new Bloodhound({
              datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
              queryTokenizer: Bloodhound.tokenizers.whitespace,
              local: JSON.parse(n)
          });
          Resource.initialize();
      
      },  "json");

      $.post(baseUrl+"task/findStake",{
          project : idproject
      }, function(data){
          var auto = createJSON(data);
          var n = createString(auto);
          Stakeholder = new Bloodhound({
              datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
              queryTokenizer: Bloodhound.tokenizers.whitespace,
              local: JSON.parse(n)
          });
          Stakeholder.initialize();
      
      },  "json");   
    
    
    var task = '<?php echo json_encode($task); ?>';
    
    task = JSON.parse(task);
    task = createJSON(task);
    task = JSON.stringify(task);
  
    var data_include = '<?php echo json_encode($include); ?>';
 
  $(document).ready(function(){

      Tasks = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(task)
    });
  
    Tasks.initialize();

    var EdInclude = $('#EdInclude');
    EdInclude.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Tasks.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info" onclick="cloneModalTask($(\'#createTask\'))"> No matches.</div>'
        },
      }
    });
    add(EdInclude, data_include);

});


  function add($elt, data){
      $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name, "continent": "" });
      });
  }

</script>

<!-- /.blockJS -->