<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <div class="card s-navShadow">
               <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                     <div class="header">
                        <h4 class="title">Create Project</h4>
                     </div>
                     <div class="content">
                        <form id="editCollaboration-form">
                        <?php 
                            echo $this->tag->hiddenField (["EdIdProject", "id" => "EdIdProject" ]);
                            echo $this->tag->hiddenField (["EdId", "id" => "EdId" ]) 
                        ?>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>CollaborationSetting Name <span class="red-star" style="font-size: 14px"> *</span></label>
                                    <?php 
                                        echo $this->tag->textField(["EdCollaborationSettingName", "size" => 30, 
                                        "class" => "form-control", "id" => "EdCollaborationSettingName"]) 
                                    ?>
                                </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Description</label>
                                    <?php 
                                        echo $this->tag->textArea(["EdDescription", "rows" => 3, 
                                        "class" => "form-control", "id" => "EdDescription"]) 
                                    ?>
                                </div>
                              </div>
                           </div>
                           <div class="row">
                              <div class="col-md-12">
                                 <div class="form-group">
                                    <label>include</label>
                                    <div>
                                       <?php 
                                          echo $this->tag->textField(["EdInclude", "size" => 30, 
                                          "class" => "form-control", "id" => "EdInclude" ]) 
                                          ?> 
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <button type="button" class="btn btn-info btn-fill pull-right" id="EditColla">Save</button>
                           <div class=""></div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>



<!-- blockJS -->
<script>
    
    var task = '<?php echo json_encode($task); ?>';
    
    task = JSON.parse(task);
    task = createJSON(task);
    task = JSON.stringify(task);
  
    var data_include = '<?php echo json_encode($include); ?>';
 
  $(document).ready(function(){

    var Task = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: JSON.parse(task)
    });
  
    Task.initialize();

    var EdInclude = $('#EdInclude');
    EdInclude.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      typeaheadjs: {
        name: 'name',
        displayKey: 'text',
        source: Task.ttAdapter(),
        templates: {
          empty: '<div class="empty-message text-info"> No matches.</div>'
        },
      }
    });
    add(EdInclude, data_include);

});


  function add($elt, data){
      $.each(JSON.parse(data), function(index ,data){   
        $elt.tagsinput('add', { "value": data._id.$id, "text": data.name, "continent": "" });
      });
  }

  function createOwner($elt){
    $elt.tagsinput('add', { "value": 5555, "text": "new owner", "continent": "" });
  }

  function createJSON(data) {
        jsonObj = [];
        
        $.each(data, function(index ,data){

            item = {};
            item ["value"] = data._id.$id;
            item ["text"] = data.name;
            item ["continent"] = "";
           
            jsonObj.push(item);
        });

        item = {};
        item ["value"] = 0;
        item ["text"] = "?";
        item ["continent"] = "";
        jsonObj.push(item);
       
        return jsonObj;
  }
</script>
<!-- /.blockJS -->