<p><?php $this->flashSession->output() ?></p>
<!-- new project card -->
<ol class="breadcrumb inline-flex">
   <li class="breadcrumb-item">
      <a href="<?=$this->url->get("project/index"); ?>">Project</a>
   </li>
   <li class="breadcrumb-item active">
      <a>Collaboration Setting</a>
   </li>
</ol>
<div class="container-fluid">
   <div class="row">
      <div class="col-md-9" style="padding:0">
         <div class="col-md-4">
            <a href="<?=$this->url->get("collaborationsetting/create"); ?>">
               <div class="thumbnail s-navShadow" id="thumbnailProject">
                  <i class="fa fa-5x fa-plus" style="
                     color: #3d578a;
                     display: flex;
                     justify-content: center;
                     width: 100%;
                     height: 100%;
                     margin-top: 40px;
                     "></i>
               </div>
            </a>
         </div>
         <?php
            foreach ($collaboration->items as $key => $card) {
            ?>
         <div class="col-md-4">
            <div class="thumbnail s-navShadow">
               <div class="caption">
                  <div class="header">
                     <h4><?=$card->name?></h4>
                  </div>
                  <hr>
                  <div class="footer">
                     <a href="#" class="btn btn-info btn-xs labelInfo" role="button" data-container="body" data-placement="bottom"  data-toggle="popover" data-placement="left" data-content="<?=$pro->description?>"><i class="fa fa-info"></i></a> 
                     <a onclick="confirm('Are you sure delete <?=$card->name?>?')?deleteCollaburation('<?=$card->_id?>'):false;" class="btn btn-danger btn-xs pull-right labelDanger" role="button" style="margin-left: 3px;" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>&nbsp;
                     <a href="#" class="btn btn-primary btn-xs pull-right labelPrimary collaburationEdit" data-id="<?=$card->_id?>" role="button" data-toggle="tooltip"  data-placement="top" title="Edit"><i class="fa fa-edit"></i></a> 
                     <a class="showDetailColla btn btn-xs pull-right"  onclick="cloneModalDetailColla('<?=$card->_id?>')" role="button" style="margin-right: 3px;" data-toggle="tooltip" data-placement="top" title="Show"><i class="fa fa-eye"></i></a>&nbsp; 
                  </div>
               </div>
            </div>
         </div>
         <?php } ?>
      </div>
      <form action="<?=$this->url->get("collaborationsetting/index"); ?>" method="POST">
         <div class="col-md-3">
            <!-- Sort -->
            <div class="card s-navShadow">
               <div class="header">
                  <h4 class="title">Sort</h4>
               </div>
               <div class="content">
                  <div class="form-group">
                     <?php 
                        echo $this->tag->select(
                            [
                                    'sortBy',
                                    $arrSortBy,
                                    'value' => $sortBy,
                                    'class' => 'form-control',
                                    'id' => 'sel1',
                                    'onchange' => 'this.form.submit()'
                            ]
                        );
                        ?>
                  </div>
               </div>
            </div>
            <!-- Filter -->
            <div class="card s-navShadow">
               <div class="header">
                  <h4 class="title">Filter</h4>
               </div>
               <div class="content">
                  <div class="form-group">
                     <div class="form-group">
                        <label>Collaboration Name</label>
                        <input type="text" class="form-control"  name="filter" value="<?=$filter?>">
                     </div>
                  </div>
                  <div class="footer text-right">
                     <button class="btn btn-default" type="submit">Filter</button>
                  </div>
               </div>
            </div>
         </div>
      </form>
   </div>
</div>
<?php echo $collaboration->widgetPagination; ?>


<div class="modal showColla" id="showColla" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content card">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Collaboration Setting Details</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <div class="row">
                  <div class="col-md-6">
                     <label>Collaboration Setting name</label>
                     <h5 id="showCollaName"></h5>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <label>Description</label>
                     <h5 id="showCollaDescription"></h5>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-12">
                     <label>Includes</label>
                     <div id="showCollaInclude"></div>
                  </div>
               </div>
    
              
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- blockJS -->
<script src="<?php echo $this->url->get('/public/modal/cloneModal.js');?>"></script>
<script>
   function deleteCollaburation(id){
       var idCollaboration = id;
      
       $.post(baseUrl+"collaborationsetting/deleteCollaburation",{
           idCollaboration : idCollaboration
       }, function(data){
           window.location.href = baseUrl+"collaborationsetting";
       },  "json");
   
        
   }
</script>
<!-- /.blockJS -->