<!-- css for Semantic-->
<link href="Semantic/components/card.css" rel="stylesheet" />
<link href="Semantic/components/dropdown.css" rel="stylesheet" />
<link href="Semantic/components/dropdown.min.css" rel="stylesheet" />
<link href="Semantic/components/segment.css" rel="stylesheet" />
<link href="Semantic/components/segment.min.css" rel="stylesheet" />

<!-- css for Nav-->
<link href="pro2/css/normalize.css" rel="stylesheet" />
<link href="pro2/css/milligram.min.css" rel="stylesheet" />
<link href="pro2/css/styles.css" rel="stylesheet" />
<link href="sml/regis.css" rel="stylesheet" />
<link href="sml/navindex.css" rel="stylesheet" />
<link href="Semantic/semantic.css" rel="stylesheet" />

<!-- auto tag css edit lif  -->
<link href="jslif/bootstrap-tagsinput.css" rel="stylesheet" />
<link href="jslif/app.css" rel="stylesheet" />
<link href="jslif/sb-admin.css" rel="stylesheet" />
<link href="jslif/sb-admin-override.css" rel="stylesheet" />

</head>
<body>
   <div class="">
      <div class="navbar">
         <div class="row">
            <div class="column column-30 col-site-title"><a href="#" class="site-title float-left">SMLTOOLS</a></div>
            <div class="column column-30">
               <div class="user-section">
                  <a href="#">
                     <img src="http://via.placeholder.com/50x50" alt="profile photo" class="circle float-left profile-photo" width="50" height="auto">
                     <div class="username">
                        <h4>User Name</h4>
                        <p>Firstname</p>
                     </div>
                  </a>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="row">
      <div id="sidebar" class="column">
         <h5>Navigation</h5>
         <ul>
            <li><a href="index"><em class="fa fa-home"></em> Home</a></li>
            <li><a href="create"><em class="fa fa-bar-chart"></em> Create</a></li>
         </ul>
      </div>
      <div id="main-content" class="column column-offset-20">

      <?php echo $this->getContent(); ?>

      </div>
   </div>

   <script src="popper/popper.min.js" type="text/javascript"></script>
   <script src="pro/js/jquery-3.2.1.min.js" type="text/javascript"></script>
   <script src="bootstrap-4/js/bootstrap.min.js" type="text/javascript"></script>
   
   <script src="jslif/sb-admin.js" type="text/javascript"></script>
    <!-- tag input -->
   <script src="jslif/jquery.easing.min.js" type="text/javascript"></script>
   <script src="'https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js" type="text/javascript"></script>
   <script src="jslif/bootstrap-tagsinput.js" type="text/javascript"></script>
   <script src="jslif/bootstrap-tagsinput.min.js" type="text/javascript"></script>
   <script src="jslif/sb-admin.min.js" type="text/javascript"></script>
   <script src="jslif/tagProject.js" type="text/javascript"></script>


