<nav class="navbar sticky-top navbar-light bg-light sml-index-nav justify-content-end nav-pad">
<ul class="nav nav-pills">
  
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="auth/register">Sign Up</a>
  </li>
</ul>
</nav>


<?php echo $this->getContent(); ?>