<div class="wrapper">
   <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">
      <div class="sidebar-wrapper">
         <div class="logo">
            <a href="#" class="simple-text">
            SMLTOOLS
            </a>
         </div>
         <ul class="nav">
            <li class="active">
               <a href="#">
                  <i class="pe-7s-graph"></i>
                  <h6>Project : <?=$projectname?></h6>
                  <hr class="proSide">
                  <p>Owner : <?=$ownerLayout?></p>
               </a>
            </li>
            <li>
               <a href="<?=$this->url->get("project/index"); ?>">
                  <i class="pe-7s-user"></i>
                  <p>Dashboard</p>
               </a>
            </li>
            <li>
               <a href="<?=$this->url->get("collaborationsetting/"); ?>">
                  <i class="pe-7s-note2"></i>
                  <p>Collaboration Setting</p>
               </a>
            </li>
            <li>
               <a href="<?=$this->url->get("stakeholder/index"); ?>">
                  <i class="pe-7s-news-paper"></i>
                  <p>Stakeholder</p>
               </a>
            </li>
            <li>
               <a href="<?=$this->url->get("resource/index"); ?>">
                  <i class="pe-7s-science"></i>
                  <p>Resource</p>
               </a>
            </li>
            <li>
               <a href="<?=$this->url->get("task/"); ?>">
                  <i class="pe-7s-map-marker"></i>
                  <p>Task</p>
               </a>
            </li>
            <!-- <li>
               <a href="#">
                  <i class="pe-7s-bell"></i>
                  <p>Notifications</p>
               </a>
               </li> -->
         </ul>
      </div>
   </div>
   <div class="main-panel">
      <nav class="navbar s-navShadow navbar-default navbar-fixed">
         <div class="container-fluid">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="#">Dashboard</a>
            </div>
            <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-right">
                  <li class="separator hidden-lg"></li>
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle profile-image" data-toggle="dropdown">
                     <img src="http://placehold.it/30x30" class="img-circle special-img"><?= $userLogin ?><b class="caret"></b></a>
                     <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-cog"></i> Account</a></li>
                        <li class="divider"></li>
                        <li> <a href="<?=$this->url->get("auth/logout")?>"><i class="fa fa-sign-out"></i> Sign-out</a></li>
                     </ul>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <div class="content">
         <?php 
            //eco เนื้อหาของแต่ละหน้า
            echo $this->render->getContent($this->getContent());
                
            //ตัวแปรเก็บค่า script นำไป eco ในไฟล์ index.phtml
            $script = $this->render->getScript(
                $this->getContent()
            );
            ?>
      </div>
   </div>
</div>
<!-- ================================================== Modal Stakeholder ===================================================== -->
<div class="modal createStakeholder" id="createStakeholder" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">New Stakeholder</h4>
            <button class="btn btn-info" onclick="cloneModal($('#createStakeholder'))">+</button>
         </div>
         <div class="modal-body">
            <div class="container-fluid">
                  <ul class="nav nav-tabs" id="myTabs" role="tablist" style="
                     border-bottom: 0px">
                     <li role="presentation" class="active"><a href="#organisation" id="organisation-tab" role="tab" data-toggle="tab" aria-controls="organisation" aria-expanded="true" >Organisation</a></li>
                     <li role="presentation" class=""><a href="#individual" role="tab" id="individual-tab" data-toggle="tab" aria-controls="individual" aria-expanded="false">Individual</a></li>
                     <li role="presentation" class=""><a href="#role" role="tab" id="role-tab" data-toggle="tab" aria-controls="role" aria-expanded="false">Role</a></li>
                  </ul>
                  <div class="tab-content" id="">
                     <div class="tab-pane fade  active in" role="tabpanel" id="organisation" aria-labelledby="organisation-tab">
                        <div class="row">
                           <div class="col-md-12">
                              <div class="card">
                                 <div class="row">
                                    <div class="col-md-8 col-md-offset-2">
                                       <div class="header">
                                          <h4 class="title">Create organisation</h4>
                                       </div>
                                       <div class="content">
                                          <form>
                                           <label>
                                               <input type="checkbox" id="focal"> Focal Organisation
                                           </label>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>Name</label>
                                                      <input type="text" class="form-control" name="OStakeName" id="OStakeName" placeholder="Stakeholder Name...">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>Organisation</label>
                                                      <input type="text" class="form-control" name="OrganName" id="OrganName" placeholder="Organisation name">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>aka</label>
                                                      <input type="text" class="form-control" name="Oaka" id="Oaka" placeholder="it's alias me">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>description</label>
                                                      <textarea rows="5" class="form-control" name="Odescription" id="Odescription" placeholder="Here can be your description"></textarea>
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>concern</label>
                                                      <input type="text" class="form-control" name="Oconcern" id="Oconcern" placeholder="it's concern...">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>representative</label>
                                                      <input type="text" class="form-control" name="Orepresentative" id="Orepresentative" placeholder="">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>reports</label>
                                                      <input type="text" class="form-control" name="Oreports" id="Oreports" placeholder="">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>consults</label>
                                                      <input type="text" class="form-control" name="Oconsults" id="Oconsults" placeholder="">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>liaises</label>
                                                      <input type="text" class="form-control" name="Oliaises" id="Oliaises" placeholder="">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>delegate</label>
                                                      <input type="text" class="form-control" name="Odelegate" id="Odelegate" placeholder="">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>dTask</label>
                                                      <input type="text" class="form-control" name="OdTask" id="OdTask" placeholder="">
                                                   </div>
                                                </div>
                                                </div>
                                                <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>wishes</label>
                                                      <input type="text" class="form-control" name="Owishes" id="Owishes" placeholder="goal name">
                                                   </div>
                                                </div>
                                             </div>
                                             <button type="button" class="btn btn-info btn-fill pull-right" id="SaveOr">Save Organisation</button>
                                             <div class="clearfix"></div>
                                          </form>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="tab-pane fade" role="tabpanel" id="individual" aria-labelledby="individual-tab">
                        <div class="row">
                           <div class="col-md-12">
                              <div class="card">
                                 <div class="row">
                                    <div class="col-md-8 col-md-offset-2">
                                       <div class="header">
                                          <h4 class="title">Create individual</h4>
                                       </div>
                                       <div class="content">
                                          <form>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>Name</label>
                                                      <input type="text" name="inStakeName" id="inStakeName" class="form-control" placeholder="Stakeholder name">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>aka</label>
                                                      <input type="text" name="inaka" id="inaka" class="form-control" placeholder="it's alias me..">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>description</label>
                                                      <textarea rows="5" name="indescription" id="indescription" class="form-control" placeholder="Here can be your description"></textarea>
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>concern</label>
                                                      <input type="text" name="inconcern" id="inconcern" class="form-control" placeholder="it's concern...">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>attitude</label>
                                                      <select class="form-control" name="attitude" id="attitude">
                                                         <option>select</option>
                                                         <option value="0">positive</option>
                                                         <option value="1">neutral</option>
                                                         <option value="2">negative</option>
                                                         <option value="?">?</option>
                                                      </select>
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>domain Knowledge</label>
                                                      <select class="form-control" name="domainKnowledge" id="domainKnowledge">
                                                         <option>select</option>
                                                         <option value="0">novice</option>
                                                         <option value="1">intermediate</option>
                                                         <option value="2">expert</option>
                                                         <option value="?">?</option>
                                                      </select>
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>reports</label>
                                                      <input type="text" name="inreports" id="inreports" class="form-control" >
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>consults</label>
                                                      <input type="text" name="inconsults" id="inconsults" class="form-control" >
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>liaises</label>
                                                      <input type="text" name="inliaises" id="inliaises" class="form-control" >
                                                   </div>
                                                </div>
                                               </div>
                                               <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>delegate</label>
                                                      <input type="text" name="indelegate" id="indelegate" class="form-control" >
                                                   </div>
                                                </div>
               
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>dTask</label>
                                                      <input type="text" name="indTask" id="indTask" class="form-control" placeholder="">
                                                   </div>
                                                </div>
                                                </div>
                                                <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>wishes</label>
                                                      <input type="text" name="inwishes" id="inwishes" class="form-control" placeholder="goal name">
                                                   </div>
                                                </div>
                                             </div>
                                             <button  class="btn btn-info btn-fill pull-right" id="Savein">Save Individual</button>
                                             <div class="clearfix"></div>
                                          </form>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="tab-pane fade" role="tabpanel" id="role" aria-labelledby="role-tab">
                        <div class="row">
                           <div class="col-md-12">
                              <div class="card">
                                 <div class="row">
                                    <div class="col-md-8 col-md-offset-2">
                                       <div class="header">
                                          <h4 class="title">Create Role</h4>
                                       </div>
                                       <div class="content">
                                          <form>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>Name</label>
                                                      <input type="text" name="rStakeName" id="rStakeName" class="form-control" placeholder="Stakeholder name">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>aka</label>
                                                      <input type="text" name="raka" id="raka" class="form-control" placeholder="it's alias me..">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>is A</label>
                                                      <input type="text" name="isA" id="isA" class="form-control" placeholder="Stakeholder name">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>description</label>
                                                      <textarea rows="5" name="rdescription" id="rdescription" class="form-control" placeholder="Here can be your description"></textarea>
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>concern</label>
                                                      <input type="text" name="rconcern" id="rconcern" class="form-control" placeholder="it's concern...">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>PlayerType</label>
                                                      <select class="form-control" name="PlayerType" id="PlayerType">
                                                         <option>select</option>
                                                         <option value="0">Only one</option>
                                                         <option value="1">One</option>
                                                         <option value="2">Any</option>
                                                         <option value="3">Group</option>
                                                      </select>
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>RolePlayer</label>
                                                      <select class="form-control" name="RolePlayer" id="RolePlayer" >
                                                         <option>select</option>
                                                         <option value="0">All</option>
                                                         <option value="1">Some</option>
                                                         <option value="2">Any</option>
                                                      </select>
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>reports</label>
                                                      <input type="text" name="rreports" id="rreports" class="form-control">
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>consults</label>
                                                      <input type="text" name="rconsults" id="rconsults" class="form-control">
                                                   </div>
                                                </div>
                                             </div>
                                             <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>liaises</label>
                                                      <input type="text" name="rliaises" id="rliaises" class="form-control">
                                                   </div>
                                                </div>
                                               </div>
                                               <div class="row">
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>delegate</label>
                                                      <input type="text" name="rdelegate" id="rdelegate" class="form-control" >
                                                   </div>
                                                </div>
                                                <div class="col-md-6">
                                                   <div class="form-group">
                                                      <label>dTask</label>
                                                      <input type="text" name="rdTask" id="rdTask" class="form-control" placeholder="">
                                                   </div>
                                                </div>
                                                </div>
                                                <div class="row">
                                                <div class="col-md-12">
                                                   <div class="form-group">
                                                      <label>wishes</label>
                                                      <input type="text" name="rwishes" id="rwishes" class="form-control" placeholder="goal name">
                                                   </div>
                                                </div>
                                             </div>
                                             <button  class="btn btn-info btn-fill pull-right" id="saveR">Save Role</button>
                                             <div class="clearfix"></div>
                                          </form>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- ================================================== Modal Resource===================================================== -->
<div class="modal createResource" id="createResource" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">New Resource</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <form id="form">
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <input type="hidden" name="idProjectmodalResource" value="<?=$idProject?>" id="idProjectmodalResource">
                           <label>Resource Name</label>
                           <?php 
                              echo $this->tag->textField(["resourcename", "size" => 30, 
                              "class" => "form-control", "id" => "Modalresourcename"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>description</label>
                           <?php 
                              echo $this->tag->textArea(["Description", "class" => "form-control", 
                               "id" => "ModalDesResource" ,"rows" => 3,]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>includes</label>
                           <?php 
                              echo $this->tag->textField(["includes", "size" => 30, 
                              "class" => "form-control ModalincludesResource", "id" => "ModalincludesResource"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>r Owner</label>
                           <?php 
                              echo $this->tag->textField(["rOwner", "size" => 30, 
                              "class" => "form-control", "id" => "ModalrOwnerResource"]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>p Owner</label>
                           <?php 
                              echo $this->tag->textField(["pOwner", "size" => 30, 
                              "class" => "form-control", "id" => "ModalpOwnerResource"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>Maintainer</label>
                           <?php 
                              echo $this->tag->textField(["maintainer", "size" => 30, 
                              "class" => "form-control", "id" => "ModalmaintainerResource"]) 
                              ?>    
                        </div>
                     </div>
                  </div>
                  <div class="clearfix"></div>
               </form>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-info" id="saveResourceformModal">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<!-- ================================  modal Tasks  ============================================ -->
<div class="modal createTask" id="createTask" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">New Task</h4>
         </div>
         <div class="modal-body">
            <div class="content">
               <form id="form">
                  <div class="row">
                     <div class="col-md-6">
                        <div class="form-group">
                           <input type="hidden" name="idProjectmodalTask" value="<?=$idProject?>" id="idProjectmodalTask">
                           <label>Task name<span class="red-star" style="font-size: 14px"> *</span></label>
                           <?php 
                              echo $this->tag->textField(["Modaltaskname", "size" => 30, 
                              "class" => "form-control", "id" => "Modaltaskname" , ]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>IsA</label>
                           <?php 
                              echo $this->tag->textField(["ModalIsATask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalIsATask" ,]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>Description</label>
                           <?php 
                              echo $this->tag->textArea(["ModalDescriptionTask", "class" => "form-control", 
                               "id" => "ModalDescriptionTask" ,"rows" => 3,]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-8">
                        <div class="form-group">
                           <label>Includes</label>
                           <?php 
                              echo $this->tag->textField(["ModalincludesTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalincludesTask"]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="form-group">
                           <label>as IsState</label>
                           <?php 
                              echo $this->tag->selectStatic(["ModalasIsStateTask", "class" => "form-control", 
                              "id" => "ModalasIsStateTask" 
                              ,[
                                  "E" => "EXIST",
                                  "N" => "NEXIST",
                              ]
                              ]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-4">
                        <div class="form-group">
                           <label>Owner</label>
                           <?php 
                              echo $this->tag->textField(["ModalOwnerTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalOwnerTask" ]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="form-group">
                           <label>Collaburator</label>
                           <?php 
                              echo $this->tag->textField(["ModalCollaburatorTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalCollaburatorTask" ]) 
                              ?>  
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="form-group">
                           <label>Regulator</label>
                           <?php 
                              echo $this->tag->textField(["ModalRegulatorTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalregulatorTask"]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-8">
                        <div class="form-group">
                           <label>Uses</label>
                           <?php 
                              echo $this->tag->textField(["ModalUsesTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalUsesTask" ]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="form-group">
                           <label>to Be State</label>
                           <?php 
                              echo $this->tag->selectStatic(["ModalToBeStateTask", "class" => "form-control", 
                              "id" => "ModalToBeStateTask" 
                              ,[
                                  "E" => "EXIST",
                                  "N" => "NEXIST",
                                  "A" => "ADEPTED",
                              ]
                              ]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label>Produces</label>
                           <?php 
                              echo $this->tag->textField(["ModalProducesTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalProducesTask" ]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>owner To Be</label>
                           <?php 
                              echo $this->tag->textField(["ModalOwnerToBeTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalOwnerToBeTask"]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>collaborator To Be</label>
                           <?php 
                              echo $this->tag->textField(["ModalCollaboratorToBeTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalCollaboratorToBeTask" ]) 
                              ?>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>toUse</label>
                           <?php 
                              echo $this->tag->textField(["ModalToUseTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalToUseTask"]) 
                              ?>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="form-group">
                           <label>toProduce</label>
                           <?php 
                              echo $this->tag->textField(["ModalToProduceTask", "size" => 30, 
                              "class" => "form-control", "id" => "ModalToProduceTask"]) 
                              ?>
                        </div>
                     </div>
                  </div>
               </form>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-info" id="saveTaskformModal">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>