<div class="wrapper">
<div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">
   <div class="sidebar-wrapper">
      <div class="logo">
         <a href="#" class="simple-text">
         SMLTOOLS
         </a>
      </div>
      <ul class="nav">
         <li class="active">
            <a href="#">
               <i class="pe-7s-graph"></i>
               <h6>Project : <?=$projectname?></h6>
               <hr class="proSide">
               <p>Owner : <?=$ownerLayout?></p>
            </a>
         </li>
         <li>
            <a href="<?=$this->url->get("project/index"); ?>">
               <i class="pe-7s-user"></i>
               <p>Dashboard</p>
            </a>
         </li>
         <li>
            <a href="#">
               <i class="pe-7s-note2"></i>
               <p>Collaboration Setting</p>
            </a>
         </li>
         <li>
            <a href="<?=$this->url->get("stakeholder/index"); ?>">
               <i class="pe-7s-news-paper"></i>
               <p>Stakeholder</p>
            </a>
         </li>
         <li>
            <a href="<?=$this->url->get("resource/index"); ?>">
               <i class="pe-7s-science"></i>
               <p>Resource</p>
            </a>
         </li>
         <li>
            <a href="<?=$this->url->get("task/index"); ?>">
               <i class="pe-7s-map-marker"></i>
               <p>Task</p>
            </a>
         </li>
         <!-- <li>
            <a href="#">
               <i class="pe-7s-bell"></i>
               <p>Notifications</p>
            </a>
         </li> -->
      </ul>
   </div>
</div>
<div class="main-panel">
   <nav class="navbar s-navShadow navbar-default navbar-fixed">
      <div class="container-fluid">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dashboard</a>
         </div>
         <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
               <li>
                  <a href="#">
                     <p>Log out</p>
                  </a>
               </li>
               <li class="separator hidden-lg"></li>
            </ul>
         </div>
      </div>
   </nav>
   <div class="content">
   <?php 
   //eco เนื้อหาของแต่ละหน้า
   echo $this->render->getContent($this->getContent());
       
   //ตัวแปรเก็บค่า script นำไป eco ในไฟล์ index.phtml
   $script = $this->render->getScript(
       $this->getContent()
   );
?>
   </div>
</div>
</div>